<center>
    <img src="../images/Page de garde.png" width="1000">
</center>


<br>


<div style="text-align:left">
    <strong>Membres de l'équipe :</strong>
<ul style="margin-left:5px;">
        <li>Wassila Ennouar</li>
        <li>Salsabil Reguragui</li>
        <li>Mohamed Lamine Zoutat</li>
        <li>Farid Bandoui</li>
        <li>Abdennour Kerrouch</li>
        <li>Anis Hemaida</li>
    </ul>
</div>

<br>

<h2 id="0">
    <span style="color:#2E86C1;">
        Sommaire
    </span>
</h2>


<br>

<center>
<span style="color:#E67E22;">
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br>
<strong style="font-size:19px;">
Compréhension et Préparation des Données
</strong><br>
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
</span>
</center>

<br>


<ul style="font-size:20px;">

<li>
<a href="#11" style="color:#2E86C1;">Comprendre le contexte retail Walmart</a>
    <ul style="font-size:16px;">
        <li><a href="#111" style="color:#2E86C1;">Analyse du fonctionnement de la grande distribution</a></li>
        <li><a href="#112" style="color:#2E86C1;">Identification des décisions à soutenir (stocks, promotions)</a></li>
        <li><a href="#113" style="color:#2E86C1;">Formalisation des besoins décisionnels</a></li>
    </ul>
</li>

<li>
<a href="#12" style="color:#2E86C1;">Définir les objectifs analytiques du projet</a>
    <ul style="font-size:16px;">
         <li><a href="#121" style="color:#2E86C1;">Définir objectif 1: Prévision ventes par magasin et département</a></li>
        <li><a href="#122" style="color:#2E86C1;">Définir objectif 2: Identification facteurs influençant ventes</a></li>
        <li><a href="#123" style="color:#2E86C1;">Définir objectif 3: Aide décision stocks, promotions et achats</a></li>
    </ul>
</li>

<li>
<a href="#13" style="color:#2E86C1;">Préparer les données de ventes et vérifier leur qualité</a>
    <ul style="font-size:16px;">
        <li><a href="#131" style="color:#2E86C1;">Importation et jointure des données</a></li>
        <li><a href="#132" style="color:#2E86C1;">Vérification de la complétude des données</a></li>
        <li><a href="#133" style="color:#2E86C1;">Harmonisation des formats (dates, variables numériques)</a></li>
        <li><a href="#134" style="color:#2E86C1;">Identification des valeurs incohérences</a></li>
        <li><a href="#135" style="color:#2E86C1;">Traiter les valeurs manquantes</a></li>
        <li><a href="#136" style="color:#2E86C1;">Détecter et gérer les valeurs aberrantes</a></li>
        <li><a href="#137" style="color:#2E86C1;">Validation de la cohérence des données avant analyse</a></li>
    </ul>
</li>

<li>
<a href="#14" style="color:#2E86C1;">Analyse exploratoire et compréhension des données</a>
    <ul style="font-size:16px;">
        <li><a href="#141" style="color:#2E86C1;">Analyse de la structure et des variables du dataset</a></li>
        <li><a href="#142" style="color:#2E86C1;">Analyse descriptive des ventes par magasin et département</a></li>
        <li><a href="#143" style="color:#2E86C1;">Analyse des tendances temporelles et saisonnières</a></li>
    </ul>
</li>

<li>
<a href="#15" style="color:#2E86C1;">Analyse des facteurs influençant les ventes</a>
    <ul style="font-size:16px;">
        <li><a href="#151" style="color:#2E86C1;">Analyse de l'effet des promotions</a></li>
        <li><a href="#152" style="color:#2E86C1;">Analyse de l'impact des périodes de fêtes</a></li>
        <li><a href="#153" style="color:#2E86C1;">Analyse des variables économiques et saisonnières</a></li>
        <li><a href="#154" style="color:#2E86C1;">Étude des corrélations entre variables et ventes</a></li>
    </ul>
</li>

<li>
<a href="#16" style="color:#2E86C1;">Restitution explicative pour l'aide à la décision</a>
    <ul style="font-size:16px;">
        <li><a href="#161" style="color:#2E86C1;">Création de visualisations explicatives</a></li>
        <li><a href="#162" style="color:#2E86C1;">Synthèse des résultats analytiques</a></li>
        <li><a href="#163" style="color:#2E86C1;">Formulation de recommandations métier</a></li>
    </ul>
</li>

</ul>

<br>

<center>
<span style="color:#E67E22;">
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br>
<strong style="font-size:19px;">
Modélisation et Évaluation Prédictive
</strong><br>
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
</span>
</center>

<br>

<ul style="font-size:20px;">

<li>
<a href="#21" style="color:#2E86C1;">Préparation des données pour la modélisation</a>
    <ul style="font-size:16px;">
        <li><a href="#211" style="color:#2E86C1;">Encodage des variables catégorielles</a></li>
        <li><a href="#212" style="color:#2E86C1;">Création de variables temporelles et contextuelles</a></li>
        <li><a href="#213" style="color:#2E86C1;">Séparation des jeux d'entraînement et de test</a></li>
    </ul>
</li>

<li>
<a href="#22" style="color:#2E86C1;">Développement et entraînement des modèles de prévision</a>
    <ul style="font-size:16px;">
        <li><a href="#221" style="color:#2E86C1;">Sélection des algorithmes de prévision adaptés</a></li>
        <li><a href="#222" style="color:#2E86C1;">Entraînement des modèles sur les données historiques</a></li>
        <li><a href="#223" style="color:#2E86C1;">Ajustement des hyperparamètres</a></li>
        <li><a href="#224" style="color:#2E86C1;">Génération des prévisions</a></li>
    </ul>
</li>

<li>
<a href="#23" style="color:#2E86C1;">Évaluation et validation des performances des modèles</a>
    <ul style="font-size:16px;">
        <li><a href="#231" style="color:#2E86C1;">Choix des métriques d'évaluation</a></li>
        <li><a href="#232" style="color:#2E86C1;">Comparaison des performances des modèles</a></li>
        <li><a href="#233" style="color:#2E86C1;">Analyse des erreurs de prédiction</a></li>
        <li><a href="#234" style="color:#2E86C1;">Interprétation avec Feature Importance et SHAP</a></li>
    </ul>
</li>

<li>
<a href="#24" style="color:#2E86C1;">Validation métier des prévisions déployées</a>
    <ul style="font-size:16px;">
        <li><a href="#241" style="color:#2E86C1;">Analyse de la cohérence des prévisions déployées</a></li>
        <li><a href="#242" style="color:#2E86C1;">Comparaison avec les ventes historiques</a></li>
        <li><a href="#243" style="color:#2E86C1;">Validation finale par les utilisateurs métier</a></li>
    </ul>
</li>

</ul>

<br>

<center>
<span style="color:#E67E22;">
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br>
<strong style="font-size:19px;">
Intelligence décisionnelle & exploitation
</strong><br>
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
</span>
</center>

<br>

<ul style="font-size:20px;">

<li>
<a href="#31" style="color:#2E86C1;">Déploiement du modèle de prévision</a>
    <ul style="font-size:16px;">
        <li><a href="#311" style="color:#2E86C1;">Choix du mode de restitution (rapport, dashboard, fichier)</a></li>
        <li><a href="#312" style="color:#2E86C1;">Mise à disposition des prévisions générées</a></li>
        <li><a href="#313" style="color:#2E86C1;">Documentation du fonctionnement du modèle</a></li>
        <li><a href="#314" style="color:#2E86C1;">Définition des limites et hypothèses du modèle</a></li>
    </ul>
</li>

<li>
<a href="#32" style="color:#2E86C1;">Générer des prévisions de ventes pour la planification</a>
    <ul style="font-size:16px;">
        <li><a href="#321" style="color:#2E86C1;">Générer prévisions par magasin</a></li>
        <li><a href="#322" style="color:#2E86C1;">Générer prévisions par département</a></li>
        <li><a href="#323" style="color:#2E86C1;">Documenter méthodologie prévisions</a></li>
    </ul>
</li>

<li>
<a href="#33" style="color:#2E86C1;">Créer un système de recommandations pour la gestion</a>
    <ul style="font-size:16px;">
        <li><a href="#331" style="color:#2E86C1;">Calculer niveaux de stock optimaux</a></li>
        <li><a href="#332" style="color:#2E86C1;">Générer alertes de rupture</a></li>
        <li><a href="#333" style="color:#2E86C1;">Produire rapports recommandations</a></li>
    </ul>
</li>

<li>
<a href="#34" style="color:#2E86C1;">Développer un simulateur d'impact des promotions</a>
    <ul style="font-size:16px;">
        <li><a href="#341" style="color:#2E86C1;">Créer interface de simulation</a></li>
        <li><a href="#342" style="color:#2E86C1;">Calculer impact prévisionnel</a></li>
        <li><a href="#343" style="color:#2E86C1;">Estimer ROI et comparer scénarios</a></li>
    </ul>
</li>

<li>
<a href="#35" style="color:#2E86C1;">Créer un dashboard de visualisation et monitoring</a>
    <ul style="font-size:16px;">
        <li><a href="#351" style="color:#2E86C1;">Développer visualisations principales</a></li>
        <li><a href="#352" style="color:#2E86C1;">Créer cartes KPIs exécutifs</a></li>
        <li><a href="#353" style="color:#2E86C1;">Implémenter filtres et interactivité</a></li>
    </ul>
</li>

</ul>

<br><br>
<hr style="border: 1px solid #E67E22;">

<br>

<center>
<span id="2" style="color:#E67E22;">
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br>
<strong style="font-size:19px;">
Modélisation et Évaluation Prédictive
</strong><br>
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
</span>
</center>

## <span id="21" style="color:#2E86C1;">2.1 Préparation des données pour la modélisation</span>

Avant d'entraîner tout modèle de machine learning, les données brutes issues de l'étape `Compréhension et Préparation des Données` doivent être **transformées et structurées** de façon à être exploitables par les algorithmes de prévision. Cette phase de préparation est déterminante : la qualité des features construites conditionne directement la précision des prédictions.

Cette section couvre trois étapes structurantes :

| Étape | Contenu |
|---|---|
| **2.1.1 Encodage** | Transformation des variables catégorielles (`Store`, `Dept`, `Type`, `IsHoliday`) en valeurs numériques exploitables |
| **2.1.2 Feature engineering** | Extraction de variables temporelles (`Year`, `Month`, `Week`), indicateurs de saisonnalité et variables de contexte promotionnel |
| **2.1.3 Split train/test** | Séparation temporelle des données en jeu d'entraînement et jeu de validation, en respectant la chronologie des ventes |


> ⚠️ **Principe fondamental** : le split train/test doit être **temporel** et non aléatoire. Utiliser un split aléatoire entraînerait une **fuite de données** (*data leakage*) — le modèle verrait des semaines futures lors de l'entraînement, ce qui fausserait l'évaluation des performances.


In [ ]:
# ──────────────────────────────────────────────────────────────────
# IMPORT — Chargement de df_train_model depuis EPIC1
# ──────────────────────────────────────────────────────────────────
import pandas as pd

df_train = pd.read_parquet("../Data/prepared/df_train.parquet")

print(f"✅ df_train chargé depuis EPIC1")

df_types = pd.DataFrame({
    "Variable": df_train.columns,
    "Type": [str(t) for t in df_train.dtypes.values]
})

display(
    df_types.style
    .set_properties(**{
        "text-align": "left",
        "padding": "8px",
        "border": "1px solid #ddd"
    })
    .set_caption("Types des variables du dataset")
)

df_train.head()







✅ df_train chargé depuis EPIC1


,Variable,Type
0,Store,int64
1,Dept,int64
2,Date,datetime64[ns]
3,Weekly_Sales,float64
4,IsHoliday,bool
5,Temperature,float64
6,Fuel_Price,float64
7,MarkDown1,float64
8,MarkDown2,float64
9,MarkDown3,float64


,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size
0,1,1,2010-02-05,24924.50,False,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,A,151315
1,1,1,2010-02-12,46039.49,True,38.51,2.548,0.0,0.0,0.0,0.0,0.0,211.242170,8.106,A,151315
2,1,1,2010-02-19,41595.55,False,39.93,2.514,0.0,0.0,0.0,0.0,0.0,211.289143,8.106,A,151315
3,1,1,2010-02-26,19403.54,False,46.63,2.561,0.0,0.0,0.0,0.0,0.0,211.319643,8.106,A,151315
4,1,1,2010-03-05,21827.90,False,46.50,2.625,0.0,0.0,0.0,0.0,0.0,211.350143,8.106,A,151315


<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="211" style="color:#2E86C1;">2.1.1 Encodage des variables catégorielles</span>

Le dataset issu de l'EPIC1 contient **deux variables catégorielles à haute cardinalité** (`Store` : 45, `Dept` : 81) et **deux variables à faible cardinalité** (`Type` : 3, `IsHoliday` : 2). Chaque type nécessite une stratégie d'encodage adaptée :

| Variable | Type actuel | Modalités | Stratégie | Justification |
|---|---|---|---|---|
| `Store` | int64 | 45 | **Target Encoding** (lissé) | Encode le niveau moyen de ventes par magasin — évite 45 colonnes One-Hot |
| `Dept` | int64 | 81 | **Target Encoding** (lissé) | Encode le niveau moyen de ventes par département — évite 81 colonnes One-Hot |
| `Type` | category | A, B, C | **Ordinal Encoding** (A=1, B=2, C=3) | Variable ordinale liée à `Size` (A = grands magasins → C = petits) |
| `IsHoliday` | bool | True / False | Conversion `int` (0/1) | Déjà binaire |

**Pourquoi le Target Encoding pour Store et Dept ?**
- Le One-Hot créerait **45 + 81 = 126 colonnes** supplémentaires, alourdissant le modèle
- Le Target Encoding résume chaque catégorie par sa **moyenne de `Weekly_Sales`**, capturant le niveau de ventes propre à chaque magasin/département
- Un **lissage (smoothing)** est appliqué pour éviter la fuite de données (*target leakage*) : les moyennes bruitées des petits groupes sont régularisées vers la moyenne globale.



In [ ]:
# ══════════════════════════════════════════════════════════════════════════════
# 2.1.1 — Encodage des variables catégorielles
# ══════════════════════════════════════════════════════════════════════════════
import numpy as np

print("=" * 70)
print("  ENCODAGE DES VARIABLES CATÉGORIELLES")
print("=" * 70)

# ── 1) Target Encoding — Store (lissé avec smoothing) ────────────────────────
print("\n── 1) Target Encoding : Store ──")

global_mean = df_train['Weekly_Sales'].mean()
smoothing = 100  # facteur de lissage

store_stats = df_train.groupby('Store')['Weekly_Sales'].agg(['mean', 'count'])
store_stats['Store_encoded'] = (
    (store_stats['count'] * store_stats['mean'] + smoothing * global_mean)
    / (store_stats['count'] + smoothing)
)
store_mapping = store_stats['Store_encoded'].to_dict()

# Garder Store original pour référence
df_train['Store_orig'] = df_train['Store']
df_train['Store'] = df_train['Store_orig'].map(store_mapping)

print(f"  ✅ Store → Target Encoding (smoothing={smoothing})")
print(f"     • Moyenne globale : {global_mean:,.0f} $")
print(f"     • Plage encodée  : [{df_train['Store'].min():,.0f} — {df_train['Store'].max():,.0f}] $")

# Aperçu top 5 / bottom 5
top5 = store_stats.nlargest(5, 'Store_encoded')[['mean', 'count', 'Store_encoded']]
bot5 = store_stats.nsmallest(5, 'Store_encoded')[['mean', 'count', 'Store_encoded']]
print("\n     Top 5 magasins (ventes moyennes les plus élevées) :")
for idx, row in top5.iterrows():
    print(f"       Store {idx:>2} → {row['Store_encoded']:>10,.0f} $ (moy brute: {row['mean']:>10,.0f} $, n={row['count']:>5,})")
print("     Bottom 5 magasins :")
for idx, row in bot5.iterrows():
    print(f"       Store {idx:>2} → {row['Store_encoded']:>10,.0f} $ (moy brute: {row['mean']:>10,.0f} $, n={row['count']:>5,})")

# ── 2) Target Encoding — Dept (lissé avec smoothing) ─────────────────────────
print("\n── 2) Target Encoding : Dept ──")

dept_stats = df_train.groupby('Dept')['Weekly_Sales'].agg(['mean', 'count'])
dept_stats['Dept_encoded'] = (
    (dept_stats['count'] * dept_stats['mean'] + smoothing * global_mean)
    / (dept_stats['count'] + smoothing)
)
dept_mapping = dept_stats['Dept_encoded'].to_dict()

df_train['Dept_orig'] = df_train['Dept']
df_train['Dept'] = df_train['Dept_orig'].map(dept_mapping)

print(f"  ✅ Dept → Target Encoding (smoothing={smoothing})")
print(f"     • Plage encodée : [{df_train['Dept'].min():,.0f} — {df_train['Dept'].max():,.0f}] $")
print(f"     • Nb départements : {len(dept_mapping)}")

# ── 3) Ordinal Encoding — Type (A, B, C) → lié à Size ────────────────────────
print("\n── 3) Ordinal Encoding : Type ──")

type_mapping = {'A': 1, 'B': 2, 'C': 3}
df_train['Type'] = df_train['Type'].map(type_mapping)

print(f"  ✅ Type → Ordinal Encoding (A=1, B=2, C=3)")
print(f"     • Justification : Type est lié à Size (A = grands magasins → C = petits)")
for label, code in type_mapping.items():
    n = (df_train['Type'] == code).sum()
    print(f"     • Type {label} (={code}) : {n:,} lignes ({n/len(df_train)*100:.1f}%)")

# ── 4) IsHoliday — conversion bool → int (0/1) ──────────────────────────────
print("\n── 4) IsHoliday ──")
df_train['IsHoliday'] = df_train['IsHoliday'].astype(int)
n_holiday = df_train['IsHoliday'].sum()
print(f"  ✅ IsHoliday → int (True→1, False→0)")
print(f"     • Type après conversion : {df_train['IsHoliday'].dtype}")
print(f"     • Semaines normales : {len(df_train) - n_holiday:,}")
print(f"     • Semaines de fête  : {n_holiday:,} ({n_holiday/len(df_train)*100:.1f}%)")

# ── 5) Vérification finale ───────────────────────────────────────────────────
print("\n" + "=" * 70)
print("  VÉRIFICATION APRÈS ENCODAGE")
print("=" * 70)

print(f"\n  ► Shape : {df_train.shape[0]:,} lignes × {df_train.shape[1]} colonnes")
print(f"  ► Colonnes catégorielles restantes : {list(df_train.select_dtypes(include='category').columns)}")

df_types_after = pd.DataFrame({
    "Variable": df_train.columns,
    "Type": [str(t) for t in df_train.dtypes.values],
    "Exemple": [str(df_train[c].iloc[0]) for c in df_train.columns]
})

display(
    df_types_after.style
    .set_properties(**{"text-align": "left", "padding": "8px", "border": "1px solid #ddd"})
    .set_caption("Types des variables après encodage")

)

df_train.head()



  ENCODAGE DES VARIABLES CATÉGORIELLES

── 1) Target Encoding : Store ──
  ✅ Store → Target Encoding (smoothing=100)
     • Moyenne globale : 16,026 $
     • Plage encodée  : [5,185 — 29,488] $

     Top 5 magasins (ventes moyennes les plus élevées) :
       Store 20 →     29,488 $ (moy brute:     29,621 $, n=10,105.0)
       Store  4 →     29,046 $ (moy brute:     29,174 $, n=10,196.0)
       Store 14 →     28,797 $ (moy brute:     28,925 $, n=9,938.0)
       Store 13 →     27,287 $ (moy brute:     27,394 $, n=10,459.0)
       Store  2 →     26,850 $ (moy brute:     26,956 $, n=10,216.0)
     Bottom 5 magasins :
       Store  5 →      5,185 $ (moy brute:      5,064 $, n=8,919.0)
       Store 33 →      5,892 $ (moy brute:      5,736 $, n=6,479.0)
       Store 44 →      6,199 $ (moy brute:      6,061 $, n=7,143.0)
       Store  3 →      6,485 $ (moy brute:      6,380 $, n=9,027.0)
       Store 38 →      7,616 $ (moy brute:      7,502 $, n=7,353.0)

── 2) Target Encoding : Dept ──
  ✅ De

,Variable,Type,Exemple
0,Store,float64,21687.419288029396
1,Dept,float64,19170.90525737955
2,Date,datetime64[ns],2010-02-05 00:00:00
3,Weekly_Sales,float64,24924.5
4,IsHoliday,int64,0
5,Temperature,float64,42.31
6,Fuel_Price,float64,2.572
7,MarkDown1,float64,0.0
8,MarkDown2,float64,0.0
9,MarkDown3,float64,0.0


,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size,Store_orig,Dept_orig
0,21687.419288,19170.905257,2010-02-05,24924.50,0,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,1,151315,1,1
1,21687.419288,19170.905257,2010-02-12,46039.49,1,38.51,2.548,0.0,0.0,0.0,0.0,0.0,211.242170,8.106,1,151315,1,1
2,21687.419288,19170.905257,2010-02-19,41595.55,0,39.93,2.514,0.0,0.0,0.0,0.0,0.0,211.289143,8.106,1,151315,1,1
3,21687.419288,19170.905257,2010-02-26,19403.54,0,46.63,2.561,0.0,0.0,0.0,0.0,0.0,211.319643,8.106,1,151315,1,1
4,21687.419288,19170.905257,2010-03-05,21827.90,0,46.50,2.625,0.0,0.0,0.0,0.0,0.0,211.350143,8.106,1,151315,1,1


<div style="background:#1e1e2e; border-left:4px solid #f9e2af; padding:14px 18px; border-radius:8px; margin-top:12px; color:#cdd6f4;">

**Commentaire — Résultats de l'encodage :**

Les 4 transformations appliquées ont converti l'ensemble des variables catégorielles en valeurs numériques exploitables par les algorithmes de machine learning :
- **Store** et **Dept** ont été encodés via un **Target Encoding lissé** (smoothing = 100). Le lissage régularise les moyennes des groupes à faible effectif vers la moyenne globale, limitant ainsi le risque de *target leakage*. Les colonnes `Store_orig` et `Dept_orig` sont conservées pour référence.
- **Type** a été converti en **Ordinal Encoding** (A=1, B=2, C=3), reflétant le lien ordinal avec la taille des magasins (`Size`) : les magasins de Type A sont les plus grands, ceux de Type C les plus petits.

- **IsHoliday** a été converti de `bool` en `int64` (0/1), format attendu par les modèles.

>  **Résultat** : le dataset ne contient plus aucune colonne catégorielle (`category`). Toutes les variables sont désormais numériques (`float64`, `int64` ou `int32`), prêtes pour les étapes de feature engineering et de modélisation.

</div>







<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="212" style="color:#2E86C1;">2.1.2 Création de variables temporelles et contextuelles</span>

<div style="background:#2a2a3e; border-left:4px solid #89b4fa; padding:10px 14px; border-radius:5px; margin-top:16px; color:#FAD7A0;">
<strong>Transformation de la variable Date</strong>
</div>

La colonne `Date` (datetime64) ne peut pas être utilisée telle quelle par les algorithmes de machine learning. Elle doit être **décomposée en composantes temporelles** qui capturent les cycles et tendances des ventes.

| Variable créée | Source | Rôle |
|---|---|---|
| `Year` | `Date.year` | Capturer la tendance annuelle (croissance/déclin) |
| `Month` | `Date.month` | Saisonnalité mensuelle |
| `Week` | `Date.isocalendar().week` | Numéro de semaine ISO — granularité principale des ventes |
| `Month_sin` / `Month_cos` | sin/cos(2π × Month/12) | Encodage cyclique du mois (décembre ↔ janvier sont proches) |
| `Week_sin` / `Week_cos` | sin/cos(2π × Week/52) | Encodage cyclique de la semaine (sem. 52 ↔ sem. 1 sont proches) |

> 💡 **Pourquoi l'encodage cyclique ?** Le mois 12 (décembre) et le mois 1 (janvier) sont séparés de 11 unités avec un encodage linéaire, alors qu'ils sont **voisins dans le calendrier**. L'encodage sin/cos projette le temps sur un cercle, préservant cette proximité naturelle.

In [ ]:

print("=" * 70)
print("  TRANSFORMATION DE LA VARIABLE TEMPORELLE (Date)")
print("=" * 70)

# ── 1) Variables temporelles de base ─────────────────────────────────────────
print("\n── 1) Variables temporelles de base ──")

df_train['Year']  = df_train['Date'].dt.year
df_train['Month'] = df_train['Date'].dt.month
df_train['Week']  = df_train['Date'].dt.isocalendar().week.astype(int)

print(f"  ✅ Year  → {df_train['Year'].unique()}")
print(f"  ✅ Month → {sorted(df_train['Month'].unique())}")
print(f"  ✅ Week  → [{df_train['Week'].min()} — {df_train['Week'].max()}]")

# ── 2) Encodage cyclique (sin/cos) ──────────────────────────────────────────
print("\n── 2) Encodage cyclique (sin/cos) ──")

df_train['Month_sin'] = np.sin(2 * np.pi * df_train['Month'] / 12)
df_train['Month_cos'] = np.cos(2 * np.pi * df_train['Month'] / 12)
df_train['Week_sin']  = np.sin(2 * np.pi * df_train['Week'] / 52)
df_train['Week_cos']  = np.cos(2 * np.pi * df_train['Week'] / 52)

print(f"  ✅ Month_sin / Month_cos créés")
print(f"  ✅ Week_sin  / Week_cos  créés")
print(f"     • Exemple (semaine 1)  : sin={np.sin(2*np.pi*1/52):.4f}, cos={np.cos(2*np.pi*1/52):.4f}")
print(f"     • Exemple (semaine 52) : sin={np.sin(2*np.pi*52/52):.4f}, cos={np.cos(2*np.pi*52/52):.4f}")
print(f"     → Les semaines 1 et 52 sont proches sur le cercle ✓")


# ── 3) Vérification finale ───────────────────────────────────────────────────


df_types_fe = pd.DataFrame({
    "Variable": df_train.columns,
    "Type": [str(t) for t in df_train.dtypes.values],
    "Exemple": [str(df_train[c].iloc[0]) for c in df_train.columns]
})

display(
    df_types_fe.style
    .set_properties(**{"text-align": "left", "padding": "8px", "border": "1px solid #ddd"})
    .set_caption("Variables après transformation de la variable Date")
)

df_train.head()


  TRANSFORMATION DE LA VARIABLE TEMPORELLE (Date)

── 1) Variables temporelles de base ──
  ✅ Year  → [2010 2011 2012]
  ✅ Month → [np.int32(1), np.int32(2), np.int32(3), np.int32(4), np.int32(5), np.int32(6), np.int32(7), np.int32(8), np.int32(9), np.int32(10), np.int32(11), np.int32(12)]
  ✅ Week  → [1 — 52]

── 2) Encodage cyclique (sin/cos) ──
  ✅ Month_sin / Month_cos créés
  ✅ Week_sin  / Week_cos  créés
     • Exemple (semaine 1)  : sin=0.1205, cos=0.9927
     • Exemple (semaine 52) : sin=0.0000, cos=1.0000
     → Les semaines 1 et 52 sont proches sur le cercle ✓


,Variable,Type,Exemple
0,Store,float64,21687.419288029396
1,Dept,float64,19170.90525737955
2,Date,datetime64[ns],2010-02-05 00:00:00
3,Weekly_Sales,float64,24924.5
4,IsHoliday,int64,0
5,Temperature,float64,42.31
6,Fuel_Price,float64,2.572
7,MarkDown1,float64,0.0
8,MarkDown2,float64,0.0
9,MarkDown3,float64,0.0


,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,...,Size,Store_orig,Dept_orig,Year,Month,Week,Month_sin,Month_cos,Week_sin,Week_cos
0,21687.419288,19170.905257,2010-02-05,24924.50,0,42.31,2.572,0.0,0.0,0.0,...,151315,1,1,2010,2,5,0.866025,5.000000e-01,0.568065,0.822984
1,21687.419288,19170.905257,2010-02-12,46039.49,1,38.51,2.548,0.0,0.0,0.0,...,151315,1,1,2010,2,6,0.866025,5.000000e-01,0.663123,0.748511
2,21687.419288,19170.905257,2010-02-19,41595.55,0,39.93,2.514,0.0,0.0,0.0,...,151315,1,1,2010,2,7,0.866025,5.000000e-01,0.748511,0.663123
3,21687.419288,19170.905257,2010-02-26,19403.54,0,46.63,2.561,0.0,0.0,0.0,...,151315,1,1,2010,2,8,0.866025,5.000000e-01,0.822984,0.568065
4,21687.419288,19170.905257,2010-03-05,21827.90,0,46.50,2.625,0.0,0.0,0.0,...,151315,1,1,2010,3,9,1.000000,6.123234e-17,0.885456,0.464723


<div style="background:#1e1e2e; border-left:4px solid #f9e2af; padding:14px 18px; border-radius:8px; margin-top:12px; color:#cdd6f4;">

**Commentaire - Résultats de la transformation de la variable Date :**

La colonne `Date` a été décomposée en **7 nouvelles variables** numériques :

- **`Year`**, **`Month`**, **`Week`** : composantes calendaires directes, capturant respectivement la tendance annuelle, la saisonnalité mensuelle et la granularité hebdomadaire des ventes.

- **`Month_sin`/`Month_cos`** et **`Week_sin`/`Week_cos`** : encodage cyclique via sin/cos. Cette transformation projette le temps sur un cercle unitaire, permettant aux modèles de comprendre que **décembre (12) et janvier (1) sont voisins**, et que **la semaine 52 et la semaine 1 sont consécutives**.


</div>



<div style="background:#2a2a3e; border-left:4px solid #89b4fa; padding:10px 14px; border-radius:5px; margin-top:16px; color:#FAD7A0;">
<strong>Transformation des variables Markdown</strong>
</div>

Les variables `MarkDown1` à `MarkDown5` représentent les montants de réductions promotionnelles par type. Plutôt que de les utiliser uniquement de manière individuelle, nous créons **4 variables agrégées** qui synthétisent l'activité promotionnelle globale :

| Variable créée | Calcul | Rôle |
|---|---|---|
| `MarkDown_Total` | Somme de MarkDown1 à MarkDown5 | Pression promotionnelle totale (en $) |
| `MarkDown_Density` | MarkDown_Total / Size | Pression promotionnelle **relative** à la taille du magasin ($/sqft) |
| `Has_MarkDown` | 1 si MarkDown_Total > 0, sinon 0 | Signal binaire : promo active ou non |
| `Nb_MarkDowns` | Nombre de MarkDowns > 0 | Intensité promotionnelle (combien de types de promos simultanées) |

> 💡 `MarkDown_Density` normalise le budget promo par la surface du magasin : un même montant de 50 000 $ a un impact très différent dans un grand magasin (Type A) vs un petit (Type C). Les colonnes individuelles `MarkDown1`–`MarkDown5` sont **conservées** pour distinguer l'effet de chaque type de promotion.

In [ ]:

print("=" * 70)
print("  TRANSFORMATION DES VARIABLES MARKDOWN")
print("=" * 70)

md_cols = ['MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5']

# ── 1) MarkDown_Total — pression promotionnelle totale ───────────────────────
print("\n── 1) MarkDown_Total ──")

df_train['MarkDown_Total'] = df_train[md_cols].sum(axis=1)

print(f"  ✅ MarkDown_Total = somme des 5 MarkDowns")
print(f"     • Moyenne : {df_train['MarkDown_Total'].mean():,.0f} $")
print(f"     • Médiane : {df_train['MarkDown_Total'].median():,.0f} $")
print(f"     • Max     : {df_train['MarkDown_Total'].max():,.0f} $")
print(f"     • Lignes à 0 : {(df_train['MarkDown_Total'] == 0).sum():,} ({(df_train['MarkDown_Total'] == 0).mean()*100:.1f}%)")

# ── 2) MarkDown_Density — pression promo relative à la taille du magasin ─────
print("\n── 2) MarkDown_Density ──")

df_train['MarkDown_Density'] = df_train['MarkDown_Total'] / df_train['Size']

print(f"  ✅ MarkDown_Density = MarkDown_Total / Size ($/sqft)")
print(f"     • Moyenne : {df_train['MarkDown_Density'].mean():.6f}")
print(f"     • Médiane : {df_train['MarkDown_Density'].median():.6f}")
print(f"     • Max     : {df_train['MarkDown_Density'].max():.6f}")
print(f"     • Lignes à 0 : {(df_train['MarkDown_Density'] == 0).sum():,} ({(df_train['MarkDown_Density'] == 0).mean()*100:.1f}%)")

# ── 3) Has_MarkDown — signal binaire promo active ───────────────────────────
print("\n── 3) Has_MarkDown ──")

df_train['Has_MarkDown'] = (df_train['MarkDown_Total'] > 0).astype(int)

n_promo = df_train['Has_MarkDown'].sum()
print(f"  ✅ Has_MarkDown = 1 si au moins un MarkDown > 0")
print(f"     • Semaines avec promo  : {n_promo:,} ({n_promo/len(df_train)*100:.1f}%)")
print(f"     • Semaines sans promo  : {len(df_train) - n_promo:,} ({(len(df_train) - n_promo)/len(df_train)*100:.1f}%)")

# ── 4) Nb_MarkDowns — nombre de promos actives simultanément ─────────────────
print("\n── 4) Nb_MarkDowns ──")

df_train['Nb_MarkDowns'] = (df_train[md_cols] > 0).sum(axis=1)

print(f"  ✅ Nb_MarkDowns = nombre de MarkDowns > 0 par ligne")
print(f"     • Distribution :")
for val in sorted(df_train['Nb_MarkDowns'].unique()):
    n = (df_train['Nb_MarkDowns'] == val).sum()
    print(f"       {val} promo(s) active(s) : {n:,} lignes ({n/len(df_train)*100:.1f}%)")

# ── 5) Vérification ──────────────────────────────────────────────────────────
print("\n" + "=" * 70)
print("  VÉRIFICATION")
print("=" * 70)

new_md_cols = ['MarkDown_Total', 'MarkDown_Density', 'Has_MarkDown', 'Nb_MarkDowns']
print(f"\n  ► Nouvelles colonnes : {new_md_cols}")
print(f"  ► MarkDown1-5 individuels : conservés ✓")
print(f"  ► Shape : {df_train.shape[0]:,} lignes × {df_train.shape[1]} colonnes")

# Aperçu des lignes avec promo
display(
    df_train[df_train['Has_MarkDown'] == 1][md_cols + new_md_cols].head(5)
    .style
    .set_properties(**{"text-align": "right", "padding": "6px"})
    .set_caption("Exemples de lignes avec MarkDowns actifs")
)

  TRANSFORMATION DES VARIABLES MARKDOWN

── 1) MarkDown_Total ──
  ✅ MarkDown_Total = somme des 5 MarkDowns
     • Moyenne : 6,663 $
     • Médiane : 0 $
     • Max     : 160,511 $
     • Lignes à 0 : 269,337 (64.3%)

── 2) MarkDown_Density ──
  ✅ MarkDown_Density = MarkDown_Total / Size ($/sqft)
     • Moyenne : 0.048158
     • Médiane : 0.000000
     • Max     : 1.342545
     • Lignes à 0 : 269,337 (64.3%)

── 3) Has_MarkDown ──
  ✅ Has_MarkDown = 1 si au moins un MarkDown > 0
     • Semaines avec promo  : 149,390 (35.7%)
     • Semaines sans promo  : 269,337 (64.3%)

── 4) Nb_MarkDowns ──
  ✅ Nb_MarkDowns = nombre de MarkDowns > 0 par ligne
     • Distribution :
       0 promo(s) active(s) : 269,337 lignes (64.3%)
       1 promo(s) active(s) : 201 lignes (0.0%)
       2 promo(s) active(s) : 3,897 lignes (0.9%)
       3 promo(s) active(s) : 8,804 lignes (2.1%)
       4 promo(s) active(s) : 41,301 lignes (9.9%)
       5 promo(s) active(s) : 95,187 lignes (22.7%)

  VÉRIFICATION

  ► N

,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,MarkDown_Total,MarkDown_Density,Has_MarkDown,Nb_MarkDowns
92,10382.900000,6115.670000,215.070000,2406.620000,6551.420000,25671.680000,0.169657,1,5
93,6074.120000,254.390000,51.980000,427.390000,5988.570000,12796.450000,0.084568,1,5
94,410.310000,98.000000,55805.510000,8.000000,554.920000,56876.740000,0.375883,1,5
95,5629.510000,68.000000,1398.110000,2084.640000,20475.320000,29655.580000,0.195986,1,5
96,4640.650000,19.000000,105.020000,3639.420000,14461.820000,22865.910000,0.151115,1,5


<div style="background:#1e1e2e; border-left:4px solid #f9e2af; padding:14px 18px; border-radius:8px; margin-top:12px; color:#cdd6f4;">

**Commentaire — Résultats de la transformation des MarkDowns :**

Les 5 variables promotionnelles individuelles (`MarkDown1`–`MarkDown5`) ont été conservées et complétées par **4 variables agrégées** :

- **`MarkDown_Total`** : somme des 5 MarkDowns — mesure la pression promotionnelle totale en dollars pour chaque semaine/magasin/département.

- **`MarkDown_Density`** : ratio `MarkDown_Total / Size` — normalise le budget promo par la surface du magasin ($/sqft). Un même investissement promo a un impact plus fort dans un petit magasin que dans un grand. Cette variable est particulièrement utile pour Ridge, qui ne peut pas apprendre seul les interactions entre variables.

- **`Has_MarkDown`** : indicateur binaire (0/1) — signale si au moins une promotion est active. Permet aux modèles de distinguer rapidement les semaines avec/sans promo.

- **`Nb_MarkDowns`** : nombre de types de promos simultanément actifs (0 à 5) — capture l'intensité de la stratégie promotionnelle.

> **Résultat** : le dataset passe de MarkDown1-5 (5 colonnes brutes) à **9 colonnes promotionnelles** au total (5 individuelles + 4 agrégées), offrant aux modèles à la fois le détail par type de promo et une vue synthétique de l'activité promotionnelle.

</div>

<div style="background:#2a2a3e; border-left:4px solid #89b4fa; padding:10px 14px; border-radius:5px; margin-top:16px; color:#FAD7A0;">
<strong>Création des variables de décalage temporel (Lags)</strong>
</div>

Les variables de **décalage temporel (Lags)** permettent au modèle d'utiliser les ventes passées comme prédicteurs. L'idée : les ventes d'un magasin/département la semaine dernière sont fortement prédictives des ventes de cette semaine.

| Variable créée | Décalage | Rôle |
|---|---|---|
| `Lag_1` | t − 1 semaine | Signal le plus récent — réaction rapide aux changements |
| `Lag_4` | t − 4 semaines | Tendance à moyen terme (~1 mois) |
| `Lag_12` | t − 12 semaines | Tendance trimestrielle (~3 mois) |
| `Lag_52` | t − 52 semaines | Saisonnalité annuelle (même semaine l'an dernier) |

> ⚠️ **Calcul par groupe** `(Store_orig, Dept_orig)` : chaque lag est calculé au sein de la série temporelle d'un magasin/département donné, et non sur l'ensemble du dataset. Les premières lignes de chaque groupe contiendront des `NaN` (pas d'historique disponible) — ils seront traités lors du split train/test.

In [ ]:

print("=" * 70)
print("  CRÉATION DES VARIABLES DE DÉCALAGE TEMPOREL (LAGS)")
print("=" * 70)

# ── Tri chronologique par groupe (indispensable pour les lags) ───────────────
df_train = df_train.sort_values(['Store_orig', 'Dept_orig', 'Date']).reset_index(drop=True)
print("\n  ✅ Données triées par (Store_orig, Dept_orig, Date)")

# ── Définition des lags à créer ─────────────────────────────────────────────
lag_periods = [1, 4, 12, 52]

print(f"\n── Création des Lags : {lag_periods} ──")

for lag in lag_periods:
    col_name = f'Lag_{lag}'
    df_train[col_name] = (
        df_train
        .groupby(['Store_orig', 'Dept_orig'])['Weekly_Sales']
        .shift(lag)
    )
    n_nan = df_train[col_name].isna().sum()
    n_valid = df_train[col_name].notna().sum()
    print(f"\n  ✅ {col_name} (t − {lag} semaine{'s' if lag > 1 else ''})")
    print(f"     • Valeurs valides : {n_valid:,} ({n_valid/len(df_train)*100:.1f}%)")
    print(f"     • NaN (début de série) : {n_nan:,} ({n_nan/len(df_train)*100:.1f}%)")
    if n_valid > 0:
        print(f"     • Moyenne : {df_train[col_name].mean():,.0f} $")

# ── Vérification ─────────────────────────────────────────────────────────────
print("\n" + "=" * 70)
print("  VÉRIFICATION")
print("=" * 70)

lag_cols = [f'Lag_{lag}' for lag in lag_periods]
print(f"\n  ► Nouvelles colonnes : {lag_cols}")
print(f"  ► Shape : {df_train.shape[0]:,} lignes × {df_train.shape[1]} colonnes")

# Aperçu pour un magasin/département
sample = df_train[
    (df_train['Store_orig'] == 1) & (df_train['Dept_orig'] == 1)
][['Store_orig', 'Dept_orig', 'Date', 'Weekly_Sales'] + lag_cols].head(8)

print("\n  ► Exemple : Store 1, Dept 1 (premières semaines)")
display(
    sample.style
    .set_properties(**{"text-align": "right", "padding": "6px"})
    .format({col: "{:,.0f}" for col in ['Weekly_Sales'] + lag_cols}, na_rep="NaN")
    .set_caption("Lags — Store 1, Dept 1")
)

  CRÉATION DES VARIABLES DE DÉCALAGE TEMPOREL (LAGS)

  ✅ Données triées par (Store_orig, Dept_orig, Date)

── Création des Lags : [1, 4, 12, 52] ──

  ✅ Lag_1 (t − 1 semaine)
     • Valeurs valides : 415,404 (99.2%)
     • NaN (début de série) : 3,323 (0.8%)
     • Moyenne : 16,044 $

  ✅ Lag_4 (t − 4 semaines)
     • Valeurs valides : 405,630 (96.9%)
     • NaN (début de série) : 13,097 (3.1%)
     • Moyenne : 16,089 $

  ✅ Lag_12 (t − 12 semaines)
     • Valeurs valides : 380,316 (90.8%)
     • NaN (début de série) : 38,411 (9.2%)
     • Moyenne : 16,186 $

  ✅ Lag_52 (t − 52 semaines)
     • Valeurs valides : 258,793 (61.8%)
     • NaN (début de série) : 159,934 (38.2%)
     • Moyenne : 16,266 $

  VÉRIFICATION

  ► Nouvelles colonnes : ['Lag_1', 'Lag_4', 'Lag_12', 'Lag_52']
  ► Shape : 418,727 lignes × 33 colonnes

  ► Exemple : Store 1, Dept 1 (premières semaines)


,Store_orig,Dept_orig,Date,Weekly_Sales,Lag_1,Lag_4,Lag_12,Lag_52
0,1,1,2010-02-05 00:00:00,"24,924",NaN,NaN,NaN,NaN
1,1,1,2010-02-12 00:00:00,"46,039","24,924",NaN,NaN,NaN
2,1,1,2010-02-19 00:00:00,"41,596","46,039",NaN,NaN,NaN
3,1,1,2010-02-26 00:00:00,"19,404","41,596",NaN,NaN,NaN
4,1,1,2010-03-05 00:00:00,"21,828","19,404","24,924",NaN,NaN
5,1,1,2010-03-12 00:00:00,"21,043","21,828","46,039",NaN,NaN
6,1,1,2010-03-19 00:00:00,"22,137","21,043","41,596",NaN,NaN
7,1,1,2010-03-26 00:00:00,"26,229","22,137","19,404",NaN,NaN


<div style="background:#1e1e2e; border-left:4px solid #f9e2af; padding:14px 18px; border-radius:8px; margin-top:12px; color:#cdd6f4;">

**Commentaire — Résultats de la création des Lags :**

Quatre variables de décalage temporel ont été créées, calculées **par groupe** `(Store_orig, Dept_orig)` pour éviter toute contamination entre séries :

- **`Lag_1`** (t − 1 sem.) : signal le plus récent — capture les variations hebdomadaires immédiates. Très peu de NaN (1 ligne par groupe).

- **`Lag_4`** (t − 4 sem.) : tendance mensuelle — lisse les fluctuations hebdomadaires et révèle la dynamique à court terme.

- **`Lag_12`** (t − 12 sem.) : tendance trimestrielle — capture les cycles promotionnels et les variations saisonnières intra-annuelles.

- **`Lag_52`** (t − 52 sem.) : saisonnalité annuelle — les ventes de la même semaine l'année précédente sont un prédicteur très puissant en retail (ex: Black Friday, rentrée scolaire).

> **NaN attendus** : les premières semaines de chaque série (Store × Dept) n'ont pas d'historique suffisant, générant des NaN. Le `Lag_52` produit le plus de NaN (~52 lignes par groupe × 3 645 groupes). Ces valeurs manquantes seront gérées lors du split train/test (les lignes sans Lag_52 correspondent à la première année de données).

</div>

<div style="background:#2a2a3e; border-left:4px solid #89b4fa; padding:10px 14px; border-radius:5px; margin-top:16px; color:#FAD7A0;">
<strong>Création des moyennes mobiles (Moving Averages)</strong>
</div>

Les moyennes mobiles capturent la **tendance locale** des ventes en lissant les fluctuations hebdomadaires. Contrairement aux lags (valeurs ponctuelles), elles résument le comportement récent sur une fenêtre glissante.

> ⚠️ Pour éviter toute fuite de données, chaque moyenne mobile est **décalée d'une semaine** (`shift(1)`) — la semaine courante n'entre jamais dans le calcul.

| Variable | Description |
|----------|-------------|
| `MA_4` | Moyenne mobile sur **4 semaines** — tendance court terme |
| `MA_12` | Moyenne mobile sur **12 semaines** — tendance moyen terme |

Calcul par groupe `(Store × Dept)` pour respecter la granularité des séries.

In [ ]:
# ── Moyennes Mobiles (Moving Averages) ──────────────────────────────────────
ma_windows = [4, 12]
group = df_train.groupby(['Store_orig', 'Dept_orig'])['Weekly_Sales']

ma_cols = []
for w in ma_windows:
    col = f'MA_{w}'
    # rolling sur la fenêtre w, shift(1) pour exclure la semaine courante
    df_train[col] = group.transform(
        lambda x: x.rolling(window=w, min_periods=1).mean().shift(1)
    )
    ma_cols.append(col)

print(f"Colonnes créées : {ma_cols}")
print(f"Shape : {df_train.shape}")
print(f"NaN introduits :\n{df_train[ma_cols].isna().sum()}\n")

# Aperçu pour Store 1, Dept 1
sample = df_train[
    (df_train['Store_orig'] == 1) & (df_train['Dept_orig'] == 1)
][['Date', 'Weekly_Sales', 'Lag_1'] + ma_cols].head(15)
sample

Colonnes créées : ['MA_4', 'MA_12']
Shape : (418727, 35)
NaN introduits :
MA_4     3323
MA_12    3323
dtype: int64



,Date,Weekly_Sales,Lag_1,MA_4,MA_12
0,2010-02-05,24924.50,NaN,NaN,NaN
1,2010-02-12,46039.49,24924.50,24924.500000,24924.500000
2,2010-02-19,41595.55,46039.49,35481.995000,35481.995000
3,2010-02-26,19403.54,41595.55,37519.846667,37519.846667
4,2010-03-05,21827.90,19403.54,32990.770000,32990.770000
5,2010-03-12,21043.39,21827.90,32216.620000,30758.196000
6,2010-03-19,22136.64,21043.39,25967.595000,29139.061667
7,2010-03-26,26229.21,22136.64,21102.867500,28138.715714
8,2010-04-02,57258.43,26229.21,22809.285000,27900.027500
9,2010-04-09,42960.91,57258.43,31666.917500,31162.072222


<div style="background:#1e1e2e; border-left:4px solid #f9e2af; padding:14px 18px; border-radius:8px; margin-top:12px; color:#cdd6f4;">

**Résultat — Moyennes Mobiles**

| Élément | Détail |
|---------|--------|
| **Colonnes créées** | `MA_4` (4 semaines), `MA_12` (12 semaines) |
| **Shape** | 418 727 × 35 |
| **NaN introduits** | 3 323 par colonne (1ère semaine de chaque groupe Store × Dept) |
| **Protection anti-fuite** | `shift(1)` — la semaine courante est exclue du calcul |

**Complémentarité avec les lags :**
- Les **lags** capturent des valeurs ponctuelles passées (t-1, t-4, t-12, t-52)
- Les **moyennes mobiles** résument la tendance sur une fenêtre → plus robuste au bruit

Les NaN seront traités lors de la préparation finale avant l'entraînement.

</div>

<div style="background:#2a2a3e; border-left:4px solid #89b4fa; padding:10px 14px; border-radius:5px; margin-top:16px; color:#FAD7A0;">
<strong>Imputation des valeurs manquantes (Moyenne du groupe)</strong>
</div>

Les étapes précédentes (Lags, Moyennes Mobiles) ont introduit des **valeurs manquantes (NaN)**, principalement pour les premières semaines de chaque groupe `Store × Dept` où l'historique est insuffisant. Les variables `MarkDown1–5` contiennent aussi des NaN pour les périodes sans promotion.

**Stratégie : Moyenne du groupe (`Store_orig × Dept_orig`)**

Pour chaque colonne contenant des NaN, on remplace les valeurs manquantes par la **moyenne du groupe** (même magasin, même département). Cette approche respecte la hiérarchie naturelle des données :

$$\text{NaN}_{i,j} \leftarrow \overline{x}_{(\text{Store}=i,\, \text{Dept}=j)}$$

| Avantage | Détail |
|----------|--------|
| **Cohérence locale** | Un magasin haut de gamme (Type A) n'est pas dilué par les petits magasins |
| **Conservation des lignes** | On évite de supprimer ~160k lignes d'entraînement (38% du dataset) |
| **Robustesse** | Si un groupe n'a aucune valeur valide, on recourt à la **moyenne globale** |



In [ ]:
# ── Imputation des valeurs manquantes par la moyenne du groupe ───────────────
print("=" * 70)
print("  IMPUTATION DES VALEURS MANQUANTES — Moyenne du groupe (Store × Dept)")
print("=" * 70)

# Identifier les colonnes avec NaN
cols_with_nan = df_train.columns[df_train.isna().any()].tolist()
print(f"\n► Colonnes avec NaN : {cols_with_nan}")
print(f"► Nombre total de NaN avant imputation : {df_train[cols_with_nan].isna().sum().sum():,}")

# Détail des NaN par colonne
print("\n── Détail des NaN par colonne ──")
for col in cols_with_nan:
    n_nan = df_train[col].isna().sum()
    pct = n_nan / len(df_train) * 100
    print(f"  {col:20s} : {n_nan:>7,} NaN ({pct:.1f}%)")

# Imputation par la moyenne du groupe (Store_orig × Dept_orig)
print("\n── Imputation par groupe (Store_orig × Dept_orig) ──")
nan_before_total = df_train[cols_with_nan].isna().sum().sum()

for col in cols_with_nan:
    # Moyenne par groupe
    group_mean = df_train.groupby(['Store_orig', 'Dept_orig'])[col].transform('mean')
    # Imputer les NaN avec la moyenne du groupe
    df_train[col] = df_train[col].fillna(group_mean)

# Fallback : si un groupe entier est NaN, on utilise la moyenne globale
nan_after_group = df_train[cols_with_nan].isna().sum().sum()
if nan_after_group > 0:
    print(f"  ⚠️ {nan_after_group:,} NaN restants après imputation par groupe → fallback moyenne globale")
    for col in cols_with_nan:
        if df_train[col].isna().any():
            global_col_mean = df_train[col].mean()
            n_remaining = df_train[col].isna().sum()
            df_train[col] = df_train[col].fillna(global_col_mean)
            print(f"    {col:20s} : {n_remaining:,} NaN → remplacés par moyenne globale = {global_col_mean:.2f}")

# Vérification finale
nan_after_total = df_train[cols_with_nan].isna().sum().sum()
print(f"\n── Résultat ──")
print(f"  ✅ NaN avant  : {nan_before_total:,}")
print(f"  ✅ NaN après  : {nan_after_total}")
print(f"  ✅ Lignes conservées : {len(df_train):,} (aucune suppression)")
print(f"  ✅ Shape : {df_train.shape}")

  IMPUTATION DES VALEURS MANQUANTES — Moyenne du groupe (Store × Dept)

► Colonnes avec NaN : ['Lag_1', 'Lag_4', 'Lag_12', 'Lag_52', 'MA_4', 'MA_12']
► Nombre total de NaN avant imputation : 221,411

── Détail des NaN par colonne ──
  Lag_1                :   3,323 NaN (0.8%)
  Lag_4                :  13,097 NaN (3.1%)
  Lag_12               :  38,411 NaN (9.2%)
  Lag_52               : 159,934 NaN (38.2%)
  MA_4                 :   3,323 NaN (0.8%)
  MA_12                :   3,323 NaN (0.8%)

── Imputation par groupe (Store_orig × Dept_orig) ──
  ⚠️ 6,174 NaN restants après imputation par groupe → fallback moyenne globale
    Lag_1                : 40 NaN → remplacés par moyenne globale = 16031.44
    Lag_4                : 257 NaN → remplacés par moyenne globale = 16046.75
    Lag_12               : 1,031 NaN → remplacés par moyenne globale = 16097.24
    Lag_52               : 4,766 NaN → remplacés par moyenne globale = 16035.11
    MA_4                 : 40 NaN → remplacés par moye

<div style="background:#1e1e2e; border-left:4px solid #f9e2af; padding:14px 18px; border-radius:8px; margin-top:12px; color:#cdd6f4;">

**Résultat — Imputation des valeurs manquantes**

| Élément | Détail |
|---------|--------|
| **Colonnes imputées** | `Lag_1`, `Lag_4`, `Lag_12`, `Lag_52`, `MA_4`, `MA_12` |
| **NaN avant** | 221 411 (répartis sur 6 colonnes) |
| **NaN après** | 0 ✅ |
| **Méthode principale** | Moyenne du groupe `Store_orig × Dept_orig` |
| **Fallback** | 6 174 NaN → moyenne globale (groupes entièrement manquants) |
| **Lignes conservées** | 418 727 (aucune suppression) |

**Observations :**
- `Lag_52` concentrait **72% des NaN** (159 934) — les 52 premières semaines de chaque groupe n'ont pas d'historique à 1 an
- Les `MarkDown1–5` n'avaient **aucun NaN** (déjà traités lors de la préparation EPIC1)
- 6 174 NaN (2.8%) ont nécessité le fallback vers la moyenne globale, pour des groupes très courts sans aucune valeur valide

</div>

<div style="background:#2a2a3e; border-left:4px solid #89b4fa; padding:10px 14px; border-radius:5px; margin-top:16px; color:#FAD7A0;">
<strong>Normalisation des variables continues (StandardScaler)</strong>
</div>

Les variables continues du dataset présentent des **échelles très différentes** (ex: `Size` ~34 000–220 000 vs `Fuel_Price` ~2.5–4.5). Cette hétérogénéité pose problème pour **Ridge**, qui pénalise les coefficients proportionnellement à l'échelle des variables.

**Stratégie : `StandardScaler`** (z-score) — chaque variable est recentrée à moyenne 0 et écart-type 1 :

$$z = \frac{x - \mu}{\sigma}$$

| Colonnes normalisées | Raison |
|---|---|
| `Store`, `Dept` | Target-encoded (~1k–50k $) |
| `Temperature`, `Fuel_Price`, `CPI`, `Unemployment` | Échelles très différentes |
| `Size` | Très grande échelle (~34k–220k sqft) |
| `MarkDown1–5`, `MarkDown_Total`, `MarkDown_Density` | Promos en $ et $/sqft |
| `Month`, `Week`, `Year` | Composantes calendaires |
| `Lag_1/4/12/52`, `MA_4/12` | Même échelle que Weekly_Sales (~-4k à +700k) |

| Colonnes **exclues** | Raison |
|---|---|
| `Weekly_Sales` | Variable cible — ne pas transformer |
| `IsHoliday`, `Has_MarkDown` | Binaires (0/1) — déjà normalisées |
| `Type` | Ordinal (1/2/3) — plage réduite |
| `Nb_MarkDowns` | Compteur (0–5) — plage réduite |
| `Month_sin/cos`, `Week_sin/cos` | Cycliques — déjà dans [-1, 1] |
| `Store_orig`, `Dept_orig`, `Date` | Colonnes de référence — pas des features |

> ⚠️ **Note** : les modèles tree-based (RF, LightGBM, XGBoost) sont **invariants à l'échelle** et n'ont pas besoin de normalisation. Cette étape bénéficie principalement à **Ridge** (baseline). On normalise ici sur l'ensemble des données avant le split ; en production, le scaler serait ajusté uniquement sur le jeu d'entraînement.

In [ ]:
# ── Normalisation des variables continues (StandardScaler) ──────────────────
from sklearn.preprocessing import StandardScaler

print("=" * 70)
print("  NORMALISATION DES VARIABLES CONTINUES")
print("=" * 70)

# ── Colonnes à normaliser ────────────────────────────────────────────────────
cols_to_scale = [
    # Target-encoded
    'Store', 'Dept',
    # Variables économiques et environnementales
    'Temperature', 'Fuel_Price', 'CPI', 'Unemployment',
    # Taille du magasin
    'Size',
    # MarkDowns individuels et agrégés
    'MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5',
    'MarkDown_Total', 'MarkDown_Density',
    # Composantes calendaires
    'Year', 'Month', 'Week',
    # Lags et Moyennes Mobiles
    'Lag_1', 'Lag_4', 'Lag_12', 'Lag_52',
    'MA_4', 'MA_12',
]

# ── Colonnes exclues ─────────────────────────────────────────────────────────
cols_excluded = [
    'Weekly_Sales',                          # cible
    'IsHoliday', 'Has_MarkDown',             # binaires
    'Type', 'Nb_MarkDowns',                  # ordinal / compteur à plage réduite
    'Month_sin', 'Month_cos',                # cycliques [-1, 1]
    'Week_sin', 'Week_cos',
    'Store_orig', 'Dept_orig', 'Date',       # référence
]

print(f"\n  ► Colonnes à normaliser : {len(cols_to_scale)}")
print(f"  ► Colonnes exclues      : {len(cols_excluded)}")

# ── Aperçu AVANT normalisation ───────────────────────────────────────────────
print("\n── Statistiques AVANT normalisation (échantillon) ──")
before_stats = df_train[cols_to_scale].describe().loc[['mean', 'std', 'min', 'max']]
display(
    before_stats[['Store', 'Temperature', 'Fuel_Price', 'Size', 'CPI', 'Lag_1']].style
    .format("{:,.2f}")
    .set_caption("Avant normalisation — échelles très différentes")
)

# ── Application du StandardScaler ────────────────────────────────────────────
scaler = StandardScaler()
df_train[cols_to_scale] = scaler.fit_transform(df_train[cols_to_scale])

print("\n  ✅ StandardScaler appliqué sur les colonnes continues")
print(f"     • Moyenne après normalisation  : ~0")
print(f"     • Écart-type après normalisation : ~1")

# ── Aperçu APRÈS normalisation ───────────────────────────────────────────────
print("\n── Statistiques APRÈS normalisation (échantillon) ──")
after_stats = df_train[cols_to_scale].describe().loc[['mean', 'std', 'min', 'max']]
display(
    after_stats[['Store', 'Temperature', 'Fuel_Price', 'Size', 'CPI', 'Lag_1']].style
    .format("{:,.4f}")
    .set_caption("Après normalisation — toutes les variables sur la même échelle")
)

# ── Vérification finale ──────────────────────────────────────────────────────
print("\n" + "=" * 70)
print("  VÉRIFICATION")
print("=" * 70)
print(f"\n  ► Shape : {df_train.shape[0]:,} lignes × {df_train.shape[1]} colonnes")
print(f"  ► Colonnes normalisées : {len(cols_to_scale)}")
print(f"  ► Scaler sauvegardé en mémoire pour le déploiement (section 3.1)")

df_train.head()

  NORMALISATION DES VARIABLES CONTINUES

  ► Colonnes à normaliser : 23
  ► Colonnes exclues      : 12

── Statistiques AVANT normalisation (échantillon) ──


,Store,Temperature,Fuel_Price,Size,CPI,Lag_1
mean,"16,031.54",60.05,3.36,"136,684.82",171.20,"16,031.44"
std,"6,876.30",18.46,0.46,"61,010.37",39.16,"22,727.58"
min,"5,185.13",-2.06,2.47,"34,875.00",126.06,0.00
max,"29,487.84",100.14,4.47,"219,622.00",227.23,"693,099.36"



  ✅ StandardScaler appliqué sur les colonnes continues
     • Moyenne après normalisation  : ~0
     • Écart-type après normalisation : ~1

── Statistiques APRÈS normalisation (échantillon) ──


,Store,Temperature,Fuel_Price,Size,CPI,Lag_1
mean,0.0000,-0.0000,-0.0000,-0.0000,-0.0000,-0.0000
std,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000
min,-1.5774,-3.3656,-1.9357,-1.6687,-1.1527,-0.7054
max,1.9569,2.1722,2.4187,1.3594,1.4309,29.7906



  VÉRIFICATION

  ► Shape : 418,727 lignes × 35 colonnes
  ► Colonnes normalisées : 23
  ► Scaler sauvegardé en mémoire pour le déploiement (section 3.1)


,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,...,MarkDown_Total,MarkDown_Density,Has_MarkDown,Nb_MarkDowns,Lag_1,Lag_4,Lag_12,Lag_52,MA_4,MA_12
0,0.822519,0.190445,2010-02-05,24924.50,0,-0.961365,-1.717549,-0.425281,-0.173439,-0.084852,...,-0.451095,-0.464988,0,0,0.283688,0.282730,0.293406,0.283169,0.292492,0.310397
1,0.822519,0.190445,2010-02-12,46039.49,1,-1.167268,-1.769906,-0.425281,-0.173439,-0.084852,...,-0.451095,-0.464988,0,0,0.391290,0.282730,0.293406,0.283169,0.398929,0.402569
2,0.822519,0.190445,2010-02-19,41595.55,0,-1.090325,-1.844079,-0.425281,-0.173439,-0.084852,...,-0.451095,-0.464988,0,0,1.320338,0.282730,0.293406,0.283169,0.873199,0.882114
3,0.822519,0.190445,2010-02-26,19403.54,0,-0.727285,-1.741546,-0.425281,-0.173439,-0.084852,...,-0.451095,-0.464988,0,0,1.124807,0.282730,0.293406,0.283169,0.964744,0.974678
4,0.822519,0.190445,2010-03-05,21827.90,0,-0.734329,-1.601927,-0.425281,-0.173439,-0.084852,...,-0.451095,-0.464988,0,0,0.148371,0.390843,0.293406,0.283169,0.761287,0.768957


<div style="background:#1e1e2e; border-left:4px solid #f9e2af; padding:14px 18px; border-radius:8px; margin-top:12px; color:#cdd6f4;">

**Résultat — Normalisation (StandardScaler)**

| Élément | Détail |
|---------|--------|
| **Colonnes normalisées** | 23 variables continues |
| **Colonnes exclues** | 12 (cible, binaires, cycliques, référence) |
| **Moyenne après** | ~0 pour toutes les colonnes |
| **Écart-type après** | ~1 pour toutes les colonnes |
| **Shape** | 418 727 × 35 (inchangé) |

**Avant** : `Size` (~34k–220k) et `Fuel_Price` (~2.5–4.5) étaient sur des échelles incomparables.
**Après** : toutes les variables sont centrées-réduites, sur la même échelle.

> L'objet `scaler` est conservé en mémoire — il sera sauvegardé en pickle dans la section 3.1 (Déploiement) pour pouvoir transformer les nouvelles données en production avec les mêmes paramètres (μ, σ).

</div>

<div style="background:#2a2a3e; border-left:4px solid #89b4fa; padding:10px 14px; border-radius:5px; margin-top:16px; color:#FAD7A0;">
<strong>Sélection des colonnes pour la modélisation</strong>
</div>

Avant de séparer les données en jeux d'entraînement et de test, il faut **identifier clairement** quelles colonnes seront utilisées comme **features (X)** et laquelle est la **cible (y)**. Les colonnes auxiliaires (référence, date) doivent être exclues.

| Catégorie | Colonnes | Action |
|---|---|---|
| **Cible (y)** | `Weekly_Sales` | Variable à prédire |
| **Features (X)** | 30 colonnes | Entrées du modèle |
| **Exclues** | `Date`, `Store_orig`, `Dept_orig` | Colonnes de référence — pas des prédicteurs |

**Détail des 30 features retenues :**

| Groupe | Variables |
|---|---|
| **Identité magasin** | `Store`, `Dept`, `Type`, `Size` |
| **Économiques** | `Temperature`, `Fuel_Price`, `CPI`, `Unemployment` |
| **Promotionnelles** | `MarkDown1–5`, `MarkDown_Total`, `MarkDown_Density`, `Has_MarkDown`, `Nb_MarkDowns` |
| **Temporelles** | `Year`, `Month`, `Week`, `Month_sin/cos`, `Week_sin/cos` |
| **Fête** | `IsHoliday` |
| **Lags** | `Lag_1`, `Lag_4`, `Lag_12`, `Lag_52` |
| **Moyennes mobiles** | `MA_4`, `MA_12` |

In [ ]:
# ── Sélection des colonnes pour la modélisation ─────────────────────────────

print("=" * 70)
print("  SÉLECTION DES COLONNES POUR LA MODÉLISATION")
print("=" * 70)

# ── Variable cible ───────────────────────────────────────────────────────────
target = 'Weekly_Sales'

# ── Colonnes à exclure (référence / non-prédictives) ────────────────────────
cols_to_drop = ['Date', 'Store_orig', 'Dept_orig']

# ── Features = toutes les colonnes sauf cible et exclues ─────────────────────
feature_cols = [c for c in df_train.columns if c != target and c not in cols_to_drop]

print(f"\n  ► Variable cible     : {target}")
print(f"  ► Colonnes exclues   : {cols_to_drop}")
print(f"  ► Nombre de features : {len(feature_cols)}")

# ── Affichage organisé par groupe ────────────────────────────────────────────
groups = {
    'Identité magasin': ['Store', 'Dept', 'Type', 'Size'],
    'Économiques': ['Temperature', 'Fuel_Price', 'CPI', 'Unemployment'],
    'Promotionnelles (individuelles)': ['MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5'],
    'Promotionnelles (agrégées)': ['MarkDown_Total', 'MarkDown_Density', 'Has_MarkDown', 'Nb_MarkDowns'],
    'Temporelles': ['Year', 'Month', 'Week', 'Month_sin', 'Month_cos', 'Week_sin', 'Week_cos'],
    'Fête': ['IsHoliday'],
    'Lags': ['Lag_1', 'Lag_4', 'Lag_12', 'Lag_52'],
    'Moyennes mobiles': ['MA_4', 'MA_12'],
}

print(f"\n── Détail des {len(feature_cols)} features ──\n")
total = 0
for group_name, cols in groups.items():
    present = [c for c in cols if c in feature_cols]
    total += len(present)
    print(f"  {group_name} ({len(present)}) :")
    print(f"    → {present}")

print(f"\n  ✅ Total vérifié : {total} features")

# ── Suppression des colonnes auxiliaires ─────────────────────────────────────
print(f"\n── Suppression des colonnes auxiliaires ──")
df_model = df_train.drop(columns=cols_to_drop)
print(f"  ✅ Colonnes supprimées : {cols_to_drop}")
print(f"  ► Shape df_model : {df_model.shape[0]:,} lignes × {df_model.shape[1]} colonnes")
print(f"    ({len(feature_cols)} features + 1 cible)")

df_model.head()

  SÉLECTION DES COLONNES POUR LA MODÉLISATION

  ► Variable cible     : Weekly_Sales
  ► Colonnes exclues   : ['Date', 'Store_orig', 'Dept_orig']
  ► Nombre de features : 31

── Détail des 31 features ──

  Identité magasin (4) :
    → ['Store', 'Dept', 'Type', 'Size']
  Économiques (4) :
    → ['Temperature', 'Fuel_Price', 'CPI', 'Unemployment']
  Promotionnelles (individuelles) (5) :
    → ['MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5']
  Promotionnelles (agrégées) (4) :
    → ['MarkDown_Total', 'MarkDown_Density', 'Has_MarkDown', 'Nb_MarkDowns']
  Temporelles (7) :
    → ['Year', 'Month', 'Week', 'Month_sin', 'Month_cos', 'Week_sin', 'Week_cos']
  Fête (1) :
    → ['IsHoliday']
  Lags (4) :
    → ['Lag_1', 'Lag_4', 'Lag_12', 'Lag_52']
  Moyennes mobiles (2) :
    → ['MA_4', 'MA_12']

  ✅ Total vérifié : 31 features

── Suppression des colonnes auxiliaires ──
  ✅ Colonnes supprimées : ['Date', 'Store_orig', 'Dept_orig']
  ► Shape df_model : 418,727 lignes × 32 colon

,Store,Dept,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,...,MarkDown_Total,MarkDown_Density,Has_MarkDown,Nb_MarkDowns,Lag_1,Lag_4,Lag_12,Lag_52,MA_4,MA_12
0,0.822519,0.190445,24924.50,0,-0.961365,-1.717549,-0.425281,-0.173439,-0.084852,-0.276835,...,-0.451095,-0.464988,0,0,0.283688,0.282730,0.293406,0.283169,0.292492,0.310397
1,0.822519,0.190445,46039.49,1,-1.167268,-1.769906,-0.425281,-0.173439,-0.084852,-0.276835,...,-0.451095,-0.464988,0,0,0.391290,0.282730,0.293406,0.283169,0.398929,0.402569
2,0.822519,0.190445,41595.55,0,-1.090325,-1.844079,-0.425281,-0.173439,-0.084852,-0.276835,...,-0.451095,-0.464988,0,0,1.320338,0.282730,0.293406,0.283169,0.873199,0.882114
3,0.822519,0.190445,19403.54,0,-0.727285,-1.741546,-0.425281,-0.173439,-0.084852,-0.276835,...,-0.451095,-0.464988,0,0,1.124807,0.282730,0.293406,0.283169,0.964744,0.974678
4,0.822519,0.190445,21827.90,0,-0.734329,-1.601927,-0.425281,-0.173439,-0.084852,-0.276835,...,-0.451095,-0.464988,0,0,0.148371,0.390843,0.293406,0.283169,0.761287,0.768957


<div style="background:#1e1e2e; border-left:4px solid #f9e2af; padding:14px 18px; border-radius:8px; margin-top:12px; color:#cdd6f4;">

**Résultat — Sélection des colonnes**

| Élément | Détail |
|---------|--------|
| **Variable cible** | `Weekly_Sales` |
| **Features retenues** | 31 variables |
| **Colonnes supprimées** | `Date`, `Store_orig`, `Dept_orig` |
| **DataFrame résultant** | `df_model` — 418 727 × 32 (31 features + 1 cible) |

**Répartition des features :**
- **Identité magasin** (4) : Store, Dept, Type, Size
- **Économiques** (4) : Temperature, Fuel_Price, CPI, Unemployment
- **Promotionnelles** (9) : MarkDown1–5 + 4 agrégées
- **Temporelles** (7) : Year, Month, Week + sin/cos cycliques
- **Fête** (1) : IsHoliday
- **Lags + MA** (6) : Lag_1/4/12/52, MA_4, MA_12

> `df_model` est le DataFrame final prêt pour le split train/test. Les colonnes `Date`, `Store_orig` et `Dept_orig` ont été retirées car elles ne sont pas des prédicteurs.

</div>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="213" style="color:#2E86C1;">2.1.3 Séparation des jeux d'entraînement et de test</span>

La séparation des données doit respecter la **chronologie des ventes** pour simuler un scénario réaliste : le modèle est entraîné sur le passé et évalué sur le futur.

| Élément | Détail |
|---|---|
| **Méthode** | Split temporel (pas aléatoire) |
| **Plage des données** | Fév. 2010 → Oct. 2012 (~143 semaines) |
| **Seuil de coupure** | Dernières **12 semaines** (~3 mois) réservées au test |
| **Ratio approximatif** | ~92% train / ~8% test |

> ⚠️ **Pourquoi un split temporel ?** Un split aléatoire mélangerait des semaines de 2010 dans le test et des semaines de 2012 dans le train. Le modèle "verrait" le futur pendant l'entraînement → **data leakage**. Le split temporel garantit que le train contient uniquement des données **antérieures** au test.

In [ ]:
# ══════════════════════════════════════════════════════════════════════════════
# 2.1.3 — Séparation temporelle Train / Test
# ══════════════════════════════════════════════════════════════════════════════

print("=" * 70)
print("  SÉPARATION TEMPORELLE TRAIN / TEST")
print("=" * 70)

# ── 1) Identifier la plage temporelle ────────────────────────────────────────
print("\n── 1) Plage temporelle des données ──")

date_min = df_train['Date'].min()
date_max = df_train['Date'].max()
n_weeks = df_train['Date'].nunique()

print(f"  ► Début  : {date_min.strftime('%Y-%m-%d')}")
print(f"  ► Fin    : {date_max.strftime('%Y-%m-%d')}")
print(f"  ► Semaines uniques : {n_weeks}")

# ── 2) Définir le seuil de coupure ───────────────────────────────────────────
print("\n── 2) Seuil de coupure ──")

# Dernières 12 semaines (~3 mois) pour le test
from datetime import timedelta
split_date = date_max - timedelta(weeks=12)

print(f"  ► Date de coupure : {split_date.strftime('%Y-%m-%d')}")
print(f"  ► Train : [{date_min.strftime('%Y-%m-%d')} → {split_date.strftime('%Y-%m-%d')}]")
print(f"  ► Test  : ({split_date.strftime('%Y-%m-%d')} → {date_max.strftime('%Y-%m-%d')}]")

# ── 3) Créer le masque temporel ──────────────────────────────────────────────
print("\n── 3) Application du split ──")

mask_train = df_train['Date'] <= split_date
mask_test  = df_train['Date'] > split_date

# Appliquer sur df_model (même index que df_train)
X_train = df_model.loc[mask_train, feature_cols]
y_train = df_model.loc[mask_train, target]
X_test  = df_model.loc[mask_test, feature_cols]
y_test  = df_model.loc[mask_test, target]

print(f"  ► Train : {X_train.shape[0]:,} lignes")
print(f"  ► Test  : {X_test.shape[0]:,} lignes")


# ── 4) Résumé final ──────────────────────────────────────────────────────────
print("\n" + "=" * 70)
print("  RÉSUMÉ DU SPLIT")
print("=" * 70)

total = X_train.shape[0] + X_test.shape[0]
print(f"\n  ► X_train : {X_train.shape[0]:,} lignes × {X_train.shape[1]} features ({X_train.shape[0]/total*100:.1f}%)")
print(f"  ► X_test  : {X_test.shape[0]:,} lignes × {X_test.shape[1]} features ({X_test.shape[0]/total*100:.1f}%)")
print(f"  ► y_train : {y_train.shape[0]:,} valeurs")
print(f"  ► y_test  : {y_test.shape[0]:,} valeurs")
print(f"  ► Total   : {total:,} lignes (100% conservé)")

# Distribution de la cible
print(f"\n  ► Weekly_Sales (train) : moy={y_train.mean():,.0f} $ | med={y_train.median():,.0f} $")
print(f"  ► Weekly_Sales (test)  : moy={y_test.mean():,.0f} $ | med={y_test.median():,.0f} $")

  SÉPARATION TEMPORELLE TRAIN / TEST

── 1) Plage temporelle des données ──
  ► Début  : 2010-02-05
  ► Fin    : 2012-10-26
  ► Semaines uniques : 143

── 2) Seuil de coupure ──
  ► Date de coupure : 2012-08-03
  ► Train : [2010-02-05 → 2012-08-03]
  ► Test  : (2012-08-03 → 2012-10-26]

── 3) Application du split ──
  ► Train : 383,872 lignes
  ► Test  : 34,855 lignes

  RÉSUMÉ DU SPLIT

  ► X_train : 383,872 lignes × 31 features (91.7%)
  ► X_test  : 34,855 lignes × 31 features (8.3%)
  ► y_train : 383,872 valeurs
  ► y_test  : 34,855 valeurs
  ► Total   : 418,727 lignes (100% conservé)

  ► Weekly_Sales (train) : moy=16,057 $ | med=7,671 $
  ► Weekly_Sales (test)  : moy=15,686 $ | med=7,510 $


<div style="background:#1e1e2e; border-left:4px solid #f9e2af; padding:14px 18px; border-radius:8px; margin-top:12px; color:#cdd6f4;">

**Résultat — Séparation Train / Test**

| Élément | Détail |
|---------|--------|
| **Date de coupure** | 2012-08-03 |
| **Train** | 2010-02-05 → 2012-08-03 |
| **Test** | 2012-08-04 → 2012-10-26 (~12 semaines / 3 mois) |

| Dataset | Lignes | Features | % |
|---------|--------|----------|---|
| `X_train` | 383 872 | 31 | 91.7% |
| `X_test` | 34 855 | 31 | 8.3% |
| **Total** | **418 727** | — | **100%** |


**Distribution de la cible :**
- Train : moy = 16 057 $ | médiane = 7 671 $
- Test  : moy = 15 686 $ | médiane = 7 510 $

> Les distributions train/test sont **cohérentes** (écart < 2.5% sur la moyenne), confirmant que le split temporel ne crée pas de biais majeur.

**Pourquoi un ratio 92/8 et non 80/20 ?**
En séries temporelles, le ratio train/test est dicté par l'**horizon de prévision**, pas par une proportion arbitraire. Avec 143 semaines de données, réserver les 12 dernières semaines (~3 mois) pour le test simule un scénario business réaliste — en grande distribution, on prévoit typiquement sur un horizon de 1 à 3 mois. Un split 80/20 temporel réserverait ~29 semaines (7 mois), un horizon irréaliste. De plus, 34 855 lignes de test (45 magasins × ~80 départements × 12 semaines) suffisent largement pour une évaluation statistiquement solide. Les données sont prêtes pour l'entraînement des modèles.

</div>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

## <span id="22" style="color:#2E86C1;">2.2 Développement et entraînement des modèles de prévision</span>

Cette section porte sur le **développement et l'entraînement des modèles de prévision** des ventes hebdomadaires. À partir des données préparées en section 2.1 (`X_train` : 383 872 lignes × 31 features), nous entraînons progressivement **4 modèles** selon une approche du plus simple au plus complexe :

| # | Modèle | Type | Rôle |
|---|--------|------|------|
| 1 | **Ridge** | Régression linéaire pénalisée (L2) | **Baseline** — référence minimale à battre |
| 2 | **Random Forest** | Ensemble d'arbres (bagging) | Première approche non-linéaire |
| 3 | **LightGBM** | Gradient Boosting (histograms) | Modèle principal — rapide et performant |
| 4 | **XGBoost** | Gradient Boosting (exact/approx) | Validation croisée — robustesse |

**Métrique d'évaluation principale : WMAE** (Weighted Mean Absolute Error)

$$\text{WMAE} = \frac{1}{\sum w_i} \sum_{i=1}^{n} w_i \cdot |y_i - \hat{y}_i|$$

où $w_i = 5$ si la semaine est un **jour férié** (IsHoliday = 1), sinon $w_i = 1$.

> *« se tromper pendant une semaine fériée est **5 fois plus grave** que se tromper une semaine normale. »* 

Cette pondération reflète l'importance business des périodes de forte affluence (Thanksgiving, Noël, Super Bowl, Labour Day). Une erreur de prévision durant ces semaines coûte beaucoup plus cher : sous-estimation → rupture de stock et ventes perdues, surestimation → surplus et gaspillage.

**Démarche pour chaque modèle :**
1. Entraînement sur `X_train` / `y_train`
2. Prédiction sur `X_test`
3. Calcul de la WMAE et des métriques complémentaires (MAE, RMSE, R²)
4. Ajustement des hyperparamètres si nécessaire

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="221" style="color:#2E86C1;">2.2.1 Sélection des algorithmes de prévision adaptés</span>

Le choix des algorithmes repose sur une **stratégie progressive** : partir d'un modèle simple (baseline) puis monter en complexité pour mesurer le gain réel de chaque approche.

#### 1. Ridge Regression (Baseline)

Régression linéaire avec pénalisation **L2** ($\lambda \sum \beta_j^2$). Elle suppose une relation linéaire entre les features et les ventes. C'est la **référence minimale** : si un modèle avancé ne bat pas Ridge, il n'apporte aucune valeur.

| Avantage | Limite |
|----------|--------|
| Très rapide à entraîner | Ne capture pas les interactions non-linéaires |
| Interprétable (coefficients) | Sensible à l'échelle → nécessite la normalisation |
| Robuste au surapprentissage | Performance plafonnée sur données complexes |

#### 2. Random Forest

Ensemble de **centaines d'arbres de décision** entraînés sur des sous-échantillons aléatoires (bagging). Chaque arbre vote, et la prédiction finale est la **moyenne des votes**.

| Avantage | Limite |
|----------|--------|
| Capture les non-linéarités et interactions | Plus lent que Ridge |
| Robuste aux outliers | Moins performant que le boosting en général |
| Pas besoin de normalisation | Peut sur-apprendre si trop d'arbres peu profonds |

#### 3. LightGBM (Modèle principal)

Gradient Boosting basé sur des **histogrammes** : les arbres sont construits **séquentiellement**, chacun corrigeant les erreurs du précédent. L'approche par histogrammes rend LightGBM **très rapide** même sur de gros volumes.

| Avantage | Limite |
|----------|--------|
| Très performant sur données tabulaires | Risque de surapprentissage si mal réglé |
| Rapide (histogrammes + croissance par feuille) | Plus d'hyperparamètres à ajuster |
| Gère nativement les NaN et les catégorielles | Moins interprétable que Ridge |

#### 4. XGBoost (Validation)

Autre implémentation du Gradient Boosting, avec une **régularisation L1+L2** intégrée. Utilisé pour **valider** les résultats de LightGBM et confirmer la robustesse.

| Avantage | Limite |
|----------|--------|
| Régularisation native (L1 + L2) | Plus lent que LightGBM |
| Très utilisé en compétitions Kaggle | Consomme plus de mémoire |
| Complémentaire à LightGBM | Hyperparamètres similaires |

#### Résumé de la stratégie

```
Ridge (baseline)  →  Random Forest  →  LightGBM  →  XGBoost
   linéaire           non-linéaire      boosting      validation
   simple              intermédiaire     principal     robustesse
```

> Cette approche permet de **quantifier le gain** à chaque étape : si Ridge donne une WMAE de X et LightGBM donne Y, on sait exactement combien la complexité supplémentaire apporte.

In [ ]:
# ══════════════════════════════════════════════════════════════════════════════
# 2.2.1 — Sélection des algorithmes & Définition de la métrique WMAE
# ══════════════════════════════════════════════════════════════════════════════
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("=" * 70)
print("  SÉLECTION DES ALGORITHMES & MÉTRIQUE WMAE")
print("=" * 70)

# ── 1) Fonction WMAE ─────────────────────────────────────────────────────────
def wmae(y_true, y_pred, is_holiday):
    """
    Weighted Mean Absolute Error (métrique Walmart/Kaggle).
    Poids : 5 pour les semaines fériées, 1 sinon.
    """
    weights = np.where(is_holiday == 1, 5, 1)
    return np.sum(weights * np.abs(y_true - y_pred)) / np.sum(weights)

print("\n✅ Fonction wmae(y_true, y_pred, is_holiday) définie")

# ── 2) Récupérer IsHoliday pour le calcul des poids ─────────────────────────
# IsHoliday est dans X_train et X_test (c'est une feature)
is_holiday_train = X_train['IsHoliday'].values
is_holiday_test  = X_test['IsHoliday'].values

n_holiday_train = (is_holiday_train == 1).sum()
n_holiday_test  = (is_holiday_test == 1).sum()

print(f"\n── IsHoliday dans les données ──")
print(f"  ► Train : {n_holiday_train:,} semaines fériées ({n_holiday_train/len(X_train)*100:.1f}%)")
print(f"  ► Test  : {n_holiday_test:,} semaines fériées ({n_holiday_test/len(X_test)*100:.1f}%)")

# ── 3) Fonction d'évaluation complète ────────────────────────────────────────
def evaluate_model(name, y_true, y_pred, is_holiday):
    """Affiche toutes les métriques pour un modèle donné."""
    w = wmae(y_true, y_pred, is_holiday)
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    
    print(f"\n{'─' * 50}")
    print(f"  {name}")
    print(f"{'─' * 50}")
    print(f"  WMAE  : {w:,.0f} $")
    print(f"  MAE   : {mae:,.0f} $")
    print(f"  RMSE  : {rmse:,.0f} $")
    print(f"  R²    : {r2:.4f}")
    
    return {'model': name, 'WMAE': w, 'MAE': mae, 'RMSE': rmse, 'R2': r2}

print("✅ Fonction evaluate_model(name, y_true, y_pred, is_holiday) définie")

# ── 4) Liste des modèles à entraîner ────────────────────────────────────────
print(f"\n── Modèles sélectionnés ──")
models = {
    'Ridge': Ridge(alpha=1.0),
    'Random Forest': RandomForestRegressor(
        n_estimators=200, max_depth=20, min_samples_leaf=5,
        n_jobs=-1, random_state=42
    ),
}

# ── Détection CUDA (XGBoost uniquement) ────────────────────────────────────────────
import subprocess as _sp
try:
    _r = _sp.run(['nvidia-smi'], capture_output=True, text=True, timeout=5)
    _cuda = _r.returncode == 0
except Exception:
    _cuda = False
if _cuda:
    print("  ✅ GPU NVIDIA détecté → CUDA activé pour XGBoost")
else:
    print("  ℹ️  Pas de GPU → entraînement sur CPU")

# LightGBM et XGBoost — import conditionnel
try:
    import lightgbm as lgb
    models['LightGBM'] = lgb.LGBMRegressor(
        n_estimators=500, max_depth=8, learning_rate=0.05,
        num_leaves=63, min_child_samples=50,
        subsample=0.8, colsample_bytree=0.8,
        n_jobs=-1, random_state=42, verbose=-1
    )
    print("  ✅ LightGBM disponible")
except ImportError:
    print("  ⚠️ LightGBM non installé — pip install lightgbm")

try:
    import xgboost as xgb
    _xgb_gpu = {'device': 'cuda', 'tree_method': 'hist'} if _cuda else {}
    models['XGBoost'] = xgb.XGBRegressor(
        n_estimators=500, max_depth=8, learning_rate=0.05,
        subsample=0.8, colsample_bytree=0.8,
        reg_alpha=0.1, reg_lambda=1.0,
        n_jobs=-1, random_state=42, verbosity=0,
        **_xgb_gpu
    )
    print("  ✅ XGBoost disponible")
except ImportError:
    print("  ⚠️ XGBoost non installé — pip install xgboost")

print(f"\n► {len(models)} modèles prêts : {list(models.keys())}")

# Stockage des résultats
results = []
trained_models = {}

  SÉLECTION DES ALGORITHMES & MÉTRIQUE WMAE

✅ Fonction wmae(y_true, y_pred, is_holiday) définie

── IsHoliday dans les données ──
  ► Train : 26,606 semaines fériées (6.9%)
  ► Test  : 2,687 semaines fériées (7.7%)
✅ Fonction evaluate_model(name, y_true, y_pred, is_holiday) définie

── Modèles sélectionnés ──
  ✅ GPU NVIDIA détecté → CUDA activé pour XGBoost
  ✅ LightGBM disponible
  ✅ XGBoost disponible

► 4 modèles prêts : ['Ridge', 'Random Forest', 'LightGBM', 'XGBoost']


<div style="background:#1e1e2e; border-left:4px solid #f9e2af; padding:14px 18px; border-radius:8px; margin-top:12px; color:#cdd6f4;">

**Commentaire — Sélection des algorithmes et métrique WMAE :**

Cette cellule met en place l'infrastructure d'évaluation et les 4 modèles retenus pour la prévision des ventes :

- **Métrique WMAE** (*Weighted Mean Absolute Error*) : Les erreurs commises durant les **semaines fériées** sont pénalisées **5 fois plus** que les semaines normales, reflétant l'impact financier disproportionné d'une mauvaise prévision pendant ces périodes de forte affluence. La formule est :
$$WMAE = \frac{\sum_{i=1}^{n} w_i \cdot |y_i - \hat{y}_i|}{\sum_{i=1}^{n} w_i} \quad \text{avec } w_i = \begin{cases} 5 & \text{si semaine fériée} \\ 1 & \text{sinon} \end{cases}$$

- **4 modèles sélectionnés**, du plus simple au plus complexe :
  1. **Ridge** (régression linéaire régularisée L2) — sert de *baseline* pour mesurer l'apport des modèles non linéaires.
  2. **Random Forest** (200 arbres, profondeur max 20) — modèle d'ensemble robuste au bruit et aux outliers.
  3. **LightGBM** (500 itérations, lr=0.05) — gradient boosting optimisé pour la vitesse, idéal pour les grands volumes de données.
  4. **XGBoost** (500 itérations, lr=0.05, régularisation L1/L2) — gradient boosting avec régularisation intégrée pour limiter le surapprentissage.

- **Fonction `evaluate_model()`** : évalue chaque modèle avec 4 métriques complémentaires — WMAE (métrique principale), MAE, RMSE et R².

> **Résultat** : les 4 modèles sont initialisés et prêts pour l'entraînement.

</div>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="222" style="color:#2E86C1;">2.2.2 Entraînement des modèles sur les données historiques</span>

<div style="background:#1B2631; border-left:4px solid #2E86C1; padding:14px 18px; border-radius:8px; margin-bottom:10px; color:#D5D8DC;">

**Objectif** — Entraîner les 4 modèles sélectionnés (Ridge, Random Forest, LightGBM, XGBoost) sur le jeu d'entraînement (`X_train`, `y_train`), puis générer les prédictions sur le jeu de test (`X_test`) et évaluer chaque modèle avec l'ensemble des métriques (WMAE, MAE, RMSE, R²).

**Approche :**
- Chaque modèle est entraîné sur les **383 872 observations** du jeu d'entraînement (avant le 2012-08-03).
- Les prédictions sont ensuite générées sur les **34 855 observations** du jeu de test (12 dernières semaines).
- Le temps d'entraînement et de prédiction est mesuré pour chaque modèle afin de comparer leur efficacité computationnelle.
- Un **tableau comparatif** est produit, trié par WMAE croissant, pour identifier le modèle le plus performant.

</div>

In [ ]:
# ══════════════════════════════════════════════════════════════════════════════
# 2.2.2 — Entraînement des modèles & Évaluation initiale
# ══════════════════════════════════════════════════════════════════════════════
import time
import pandas as pd

print("=" * 70)
print("  ENTRAÎNEMENT DES MODÈLES & ÉVALUATION INITIALE")
print("=" * 70)

# ── Conversion de Type (category → int) pour XGBoost ────────────────────────
if X_train['Type'].dtype.name == 'category':
    X_train['Type'] = X_train['Type'].astype(int)
    X_test['Type']  = X_test['Type'].astype(int)
    print("  ℹ️  Colonne 'Type' convertie de category → int\n")

results = []
trained_models = {}

for name, model in models.items():
    print(f"\n{'━' * 60}")
    print(f"  ► Entraînement : {name}")
    print(f"{'━' * 60}")
    
    # ── Entraînement ──
    t0 = time.time()
    model.fit(X_train, y_train)
    train_time = time.time() - t0
    print(f"  ✅ Entraîné en {train_time:.1f} s")
    
    # ── Prédiction ──
    t0 = time.time()
    y_pred = model.predict(X_test)
    pred_time = time.time() - t0
    print(f"  ✅ Prédiction en {pred_time:.3f} s")
    
    # ── Évaluation ──
    res = evaluate_model(name, y_test.values, y_pred, is_holiday_test)
    res['Train_Time_s'] = round(train_time, 1)
    res['Pred_Time_s'] = round(pred_time, 3)
    results.append(res)
    
    # Stocker le modèle entraîné
    trained_models[name] = model

# ══════════════════════════════════════════════════════════════════════════════
# Tableau comparatif
# ══════════════════════════════════════════════════════════════════════════════
print(f"\n\n{'=' * 70}")
print("  TABLEAU COMPARATIF DES MODÈLES")
print(f"{'=' * 70}\n")

df_results = pd.DataFrame(results).sort_values('WMAE')
df_results.index = range(1, len(df_results) + 1)
df_results.index.name = 'Rang'

# Formater l'affichage
df_display = df_results.copy()
df_display['WMAE'] = df_display['WMAE'].apply(lambda x: f"{x:,.0f} $")
df_display['MAE']  = df_display['MAE'].apply(lambda x: f"{x:,.0f} $")
df_display['RMSE'] = df_display['RMSE'].apply(lambda x: f"{x:,.0f} $")
df_display['R2']   = df_display['R2'].apply(lambda x: f"{x:.4f}")
df_display['Train_Time_s'] = df_display['Train_Time_s'].apply(lambda x: f"{x:.1f} s")
df_display['Pred_Time_s']  = df_display['Pred_Time_s'].apply(lambda x: f"{x:.3f} s")

df_display.rename(columns={
    'model': 'Modèle', 'Train_Time_s': 'Temps entr.',
    'Pred_Time_s': 'Temps préd.'
}, inplace=True)

display(df_display)

# ── Meilleur modèle ──
best = df_results.iloc[0]
print(f"\n🏆 Meilleur modèle (WMAE le plus bas) : {best['model']}")
print(f"   WMAE = {best['WMAE']:,.0f} $  |  R² = {best['R2']:.4f}")

  ENTRAÎNEMENT DES MODÈLES & ÉVALUATION INITIALE
  ℹ️  Colonne 'Type' convertie de category → int


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ► Entraînement : Ridge
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ✅ Entraîné en 0.1 s
  ✅ Prédiction en 0.004 s

──────────────────────────────────────────────────
  Ridge
──────────────────────────────────────────────────
  WMAE  : 1,705 $
  MAE   : 1,621 $
  RMSE  : 3,388 $
  R²    : 0.9762

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ► Entraînement : Random Forest
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ✅ Entraîné en 95.9 s
  ✅ Prédiction en 0.138 s

──────────────────────────────────────────────────
  Random Forest
──────────────────────────────────────────────────
  WMAE  : 1,381 $
  MAE   : 1,293 $
  RMSE  : 2,939 $
  R²    : 0.9821

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ► Entraînement : LightGBM
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

,Modèle,WMAE,MAE,RMSE,R2,Temps entr.,Temps préd.
Rang,,,,,,,
1,XGBoost,"1,353 $","1,277 $","2,823 $",0.9835,4.1 s,0.040 s
2,LightGBM,"1,378 $","1,292 $","2,802 $",0.9837,4.6 s,0.107 s
3,Random Forest,"1,381 $","1,293 $","2,939 $",0.9821,95.9 s,0.138 s
4,Ridge,"1,705 $","1,621 $","3,388 $",0.9762,0.1 s,0.004 s



🏆 Meilleur modèle (WMAE le plus bas) : XGBoost
   WMAE = 1,353 $  |  R² = 0.9835


<div style="background:#1e1e2e; border-left:4px solid #f9e2af; padding:14px 18px; border-radius:8px; margin-top:12px; color:#cdd6f4;">

**Commentaire — Résultats de l'entraînement initial :**

Les 4 modèles ont été entraînés sur **383 872 observations** et évalués sur **34 855 observations** (12 dernières semaines). Le classement par WMAE est le suivant :

| Rang | Modèle | WMAE | R² | Temps entr. |
|:----:|--------|-----:|:----:|:-----------:|
| 1 | **XGBoost** | **1 343 $** | 0.9836 | 16.2 s |
| 2 | LightGBM | 1 378 $ | 0.9837 | 13.6 s |
| 3 | Random Forest | 1 381 $ | 0.9821 | 352.4 s |
| 4 | Ridge | 1 705 $ | 0.9762 | 0.5 s |

**Observations clés :**

- **XGBoost domine sur la WMAE** (1 343 $), ce qui signifie qu'il gère mieux les semaines fériées (poids ×5) que ses concurrents. LightGBM a un R² légèrement supérieur (0.9837 vs 0.9836), mais c'est la WMAE qui compte pour ce projet.

- **Les 3 modèles non linéaires** (XGBoost, LightGBM, Random Forest) sont très proches en performance (~1 350-1 380 $ de WMAE), ce qui confirme que le feature engineering réalisé en section 2.1 capture bien la structure des données.

- **Ridge (baseline linéaire)** affiche un WMAE de 1 705 $ — soit **~27 % plus élevé** que XGBoost. L'écart confirme l'apport significatif de la non-linéarité pour la prévision des ventes.

- **Efficacité computationnelle** : LightGBM (13.6 s) et XGBoost (16.2 s) sont ~25× plus rapides que Random Forest (352.4 s) pour des performances comparables. Ridge est le plus rapide (0.5 s) mais le moins précis.

> **Prochaine étape** : ces résultats sont obtenus avec les hyperparamètres par défaut. La section 2.2.3 tentera d'améliorer les performances via un ajustement fin des hyperparamètres, en se concentrant sur les 2 meilleurs modèles (XGBoost et LightGBM).

</div>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="223" style="color:#2E86C1;">2.2.3 Ajustement des hyperparamètres</span>

<div style="background:#1B2631; border-left:4px solid #2E86C1; padding:14px 18px; border-radius:8px; margin-bottom:10px; color:#D5D8DC;">

**Objectif** — Affiner les hyperparamètres des **2 meilleurs modèles** (XGBoost et LightGBM) afin de réduire davantage le WMAE par rapport aux résultats initiaux (1 343 $ et 1 378 $).

**Approche — `RandomizedSearchCV`** :
- **Pourquoi RandomizedSearchCV ?** Avec 383 872 lignes et de nombreux hyperparamètres, un `GridSearchCV` exhaustif serait prohibitif. `RandomizedSearchCV` échantillonne aléatoirement `n_iter` combinaisons dans l'espace de recherche, offrant un bon compromis entre exploration et temps de calcul.
- **Validation croisée** : 3 folds (compromis entre robustesse statistique et temps d'exécution).
- **Métrique d'optimisation** : `neg_mean_absolute_error` (proxy de la WMAE — la pondération par IsHoliday sera vérifiée après avec la vraie WMAE sur le jeu de test).
- **Espace de recherche** : les hyperparamètres les plus influents pour chaque algorithme (profondeur, taux d'apprentissage, régularisation, sous-échantillonnage).

</div>

In [ ]:
# ══════════════════════════════════════════════════════════════════════════════
# 2.2.3 — Ajustement des hyperparamètres (XGBoost & LightGBM)
# ══════════════════════════════════════════════════════════════════════════════
from sklearn.model_selection import RandomizedSearchCV, TimeSeriesSplit
import time, warnings, subprocess
warnings.filterwarnings('ignore')

print("=" * 70)
print("  AJUSTEMENT DES HYPERPARAMÈTRES — RandomizedSearchCV + TimeSeriesSplit")
print("=" * 70)

# ── Détection CUDA (XGBoost uniquement) ──────────────────────────────────────
try:
    _res = subprocess.run(['nvidia-smi'], capture_output=True, text=True, timeout=5)
    cuda_available = _res.returncode == 0
except Exception:
    cuda_available = False

if cuda_available:
    print("  ✅ GPU NVIDIA détecté → CUDA activé pour XGBoost")
    xgb_device_params = {'device': 'cuda', 'tree_method': 'hist'}
else:
    print("  ℹ️  Aucun GPU détecté → entraînement sur CPU")
    xgb_device_params = {}

print("  ℹ️  LightGBM → CPU (version pip sans support GPU)")

# ── Résultats avant tuning (section 2.2.2) ───────────────────────────────────
baseline_wmae = {
    'XGBoost':  df_results.loc[df_results['model'] == 'XGBoost', 'WMAE'].values[0],
    'LightGBM': df_results.loc[df_results['model'] == 'LightGBM', 'WMAE'].values[0],
}

# ── Tri de X_train par Date pour TimeSeriesSplit ──────────────────────────────
# Copie locale uniquement — X_train global inchangé pour les cellules suivantes
_sort_idx  = df_train.loc[X_train.index, 'Date'].sort_values().index
X_train_ts = X_train.loc[_sort_idx]
y_train_ts = y_train.loc[_sort_idx]
print(f"\n  ✅ X_train_ts trié par Date ({len(X_train_ts):,} lignes)")

tscv = TimeSeriesSplit(n_splits=3)
print(f"  ✅ TimeSeriesSplit(n_splits=3)\n")

# ══════════════════════════════════════════════════════════════════════════════
# 1) XGBoost — RandomizedSearchCV + TimeSeriesSplit
# ══════════════════════════════════════════════════════════════════════════════
print(f"{'━' * 60}")
print(f"  ► Tuning : XGBoost  (20 tirages × 3 folds)")
print(f"{'━' * 60}")

import xgboost as xgb

xgb_param_dist = {
    'n_estimators':     [300, 500, 700, 1000],
    'max_depth':        [6, 8, 10, 12],
    'learning_rate':    [0.01, 0.03, 0.05, 0.08, 0.1],
    'subsample':        [0.7, 0.8, 0.9],
    'colsample_bytree': [0.7, 0.8, 0.9],
    'reg_alpha':        [0, 0.01, 0.1, 0.5],
    'reg_lambda':       [0.5, 1.0, 2.0, 5.0],
    'min_child_weight': [3, 5, 10, 20],
}

xgb_base = xgb.XGBRegressor(
    n_jobs=-1, random_state=42, verbosity=0,
    **xgb_device_params
)

t0 = time.time()
xgb_search = RandomizedSearchCV(
    xgb_base,
    param_distributions=xgb_param_dist,
    n_iter=20,
    scoring='neg_mean_absolute_error',
    cv=tscv,
    random_state=42,
    n_jobs=1,
    verbose=0,
)
xgb_search.fit(X_train_ts, y_train_ts)
xgb_time = time.time() - t0

print(f"  ✅ Terminé en {xgb_time/60:.1f} min ({int(xgb_time)} s)")
print(f"  ► Meilleur score CV (neg_MAE) : {xgb_search.best_score_:,.0f}")
print(f"\n  Meilleurs hyperparamètres :")
for k, v in xgb_search.best_params_.items():
    print(f"    {k:20s} = {v}")

y_pred_xgb = xgb_search.best_estimator_.predict(X_test)
res_xgb = evaluate_model('XGBoost (tuné)', y_test.values, y_pred_xgb, is_holiday_test)

# ══════════════════════════════════════════════════════════════════════════════
# 2) LightGBM — RandomizedSearchCV + TimeSeriesSplit   (CPU uniquement)
# ══════════════════════════════════════════════════════════════════════════════
print(f"\n{'━' * 60}")
print(f"  ► Tuning : LightGBM  (20 tirages × 3 folds, CPU)")
print(f"{'━' * 60}")

import lightgbm as lgb

lgb_param_dist = {
    'n_estimators':      [300, 500, 700, 1000],
    'max_depth':         [6, 8, 10, 12, -1],
    'learning_rate':     [0.01, 0.03, 0.05, 0.08, 0.1],
    'num_leaves':        [31, 63, 127, 255],
    'min_child_samples': [20, 50, 100],
    'subsample':         [0.7, 0.8, 0.9],
    'colsample_bytree':  [0.7, 0.8, 0.9],
    'reg_alpha':         [0, 0.01, 0.1, 0.5],
    'reg_lambda':        [0, 0.1, 1.0, 5.0],
}

lgb_base = lgb.LGBMRegressor(
    n_jobs=-1, random_state=42, verbose=-1
)

t0 = time.time()
lgb_search = RandomizedSearchCV(
    lgb_base,
    param_distributions=lgb_param_dist,
    n_iter=20,
    scoring='neg_mean_absolute_error',
    cv=tscv,
    random_state=42,
    n_jobs=1,
    verbose=0,
)
lgb_search.fit(X_train_ts, y_train_ts)
lgb_time = time.time() - t0

print(f"  ✅ Terminé en {lgb_time/60:.1f} min ({int(lgb_time)} s)")
print(f"  ► Meilleur score CV (neg_MAE) : {lgb_search.best_score_:,.0f}")
print(f"\n  Meilleurs hyperparamètres :")
for k, v in lgb_search.best_params_.items():
    print(f"    {k:20s} = {v}")

y_pred_lgb = lgb_search.best_estimator_.predict(X_test)
res_lgb = evaluate_model('LightGBM (tuné)', y_test.values, y_pred_lgb, is_holiday_test)

# ══════════════════════════════════════════════════════════════════════════════
# 3) Tableau comparatif : Avant vs Après tuning
# ══════════════════════════════════════════════════════════════════════════════
print(f"\n\n{'=' * 70}")
print("  COMPARAISON AVANT / APRÈS TUNING")
print(f"{'=' * 70}\n")

comparison = []
for name_key, res_tuned, y_pred_tuned in [
    ('XGBoost', res_xgb, y_pred_xgb),
    ('LightGBM', res_lgb, y_pred_lgb),
]:
    before = baseline_wmae[name_key]
    after  = res_tuned['WMAE']
    delta  = after - before
    pct_change = (delta / before) * 100
    comparison.append({
        'Modèle': name_key,
        'WMAE avant': f"{before:,.0f} $",
        'WMAE après': f"{after:,.0f} $",
        'Δ WMAE': f"{delta:+,.0f} $",
        'Variation': f"{pct_change:+.1f} %",
        'R² après': f"{res_tuned['R2']:.4f}",
    })

df_comparison = pd.DataFrame(comparison)
df_comparison.index = range(1, len(df_comparison) + 1)
display(df_comparison)

# ── Mettre à jour les modèles entraînés ──────────────────────────────────────
trained_models['XGBoost']  = xgb_search.best_estimator_
trained_models['LightGBM'] = lgb_search.best_estimator_

best_tuned = min(
    [('XGBoost', res_xgb), ('LightGBM', res_lgb)],
    key=lambda x: x[1]['WMAE']
)
print(f"\n🏆 Champion après tuning : {best_tuned[0]}")
print(f"   WMAE = {best_tuned[1]['WMAE']:,.0f} $  |  R² = {best_tuned[1]['R2']:.4f}")


  AJUSTEMENT DES HYPERPARAMÈTRES — RandomizedSearchCV + TimeSeriesSplit
  ✅ GPU NVIDIA détecté → CUDA activé pour XGBoost
  ℹ️  LightGBM → CPU (version pip sans support GPU)

  ✅ X_train_ts trié par Date (383,872 lignes)
  ✅ TimeSeriesSplit(n_splits=3)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ► Tuning : XGBoost  (20 tirages × 3 folds)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ✅ Terminé en 6.6 min (396 s)
  ► Meilleur score CV (neg_MAE) : -1,796

  Meilleurs hyperparamètres :
    subsample            = 0.7
    reg_lambda           = 5.0
    reg_alpha            = 0.1
    n_estimators         = 700
    min_child_weight     = 3
    max_depth            = 12
    learning_rate        = 0.01
    colsample_bytree     = 0.7

──────────────────────────────────────────────────
  XGBoost (tuné)
──────────────────────────────────────────────────
  WMAE  : 1,304 $
  MAE   : 1,233 $
  RMSE  : 2,688 $
  R²    : 0.9850

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

,Modèle,WMAE avant,WMAE après,Δ WMAE,Variation,R² après
1,XGBoost,"1,353 $","1,304 $",-49 $,-3.6 %,0.9850
2,LightGBM,"1,378 $","1,356 $",-22 $,-1.6 %,0.9839



🏆 Champion après tuning : XGBoost
   WMAE = 1,304 $  |  R² = 0.9850


<div style="background:#1e1e2e; border-left:4px solid #f9e2af; padding:14px 18px; border-radius:8px; margin-top:12px; color:#cdd6f4;">

**Commentaire — Résultats de l'ajustement des hyperparamètres :**

Le `RandomizedSearchCV` (20 combinaisons × 3 folds) a été appliqué aux deux meilleurs modèles. Voici la comparaison avant/après :

| Modèle | WMAE avant | WMAE après | Δ WMAE | Variation | R² après |
|--------|-----------|-----------|--------|-----------|----------|
| **XGBoost** | 1 343 $ | **1 332 $** | −11 $ | −0.8 % | 0.9837 |
| LightGBM | 1 378 $ | 1 357 $ | −21 $ | −1.5 % | 0.9839 |

**Observations clés :**

- **XGBoost reste le champion** avec un WMAE de 1 332$ (−11$ par rapport aux paramètres par défaut). LightGBM progresse davantage en valeur absolue (−21$) mais reste en seconde position.

- **Les gains sont modestes** (< 2 %) — ce qui est un signe positif : cela confirme que les hyperparamètres par défaut choisis en section 2.2.1 étaient déjà bien calibrés, et que **la qualité du feature engineering** (section 2.1) est le principal moteur de la performance.

- **Le R² est quasi identique** entre les deux modèles (~0.984), ce qui signifie qu'ils expliquent la même proportion de variance. La différence se joue sur les **semaines fériées** (pondération ×5 dans la WMAE), où XGBoost est légèrement plus précis.

- **Temps de tuning** : l'ensemble de la procédure (20 × 3 folds × 2 modèles) a pris environ 53 minutes, ce qui reste raisonnable pour un dataset de 384K lignes.

> **Modèle retenu** : **XGBoost (tuné)** — WMAE = 1 332 $, R² = 0.9837. Ce modèle sera utilisé pour les prévisions finales et le déploiement.

</div>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="224" style="color:#2E86C1;">2.2.4 Génération des prévisions</span>

<div style="background:#1B2631; border-left:4px solid #2E86C1; padding:14px 18px; border-radius:8px; margin-top:12px; color:#D5D8DC;">

**Objectif :** Utiliser le modèle champion (**XGBoost tuné**, WMAE = 1 332 $) pour générer les prévisions finales sur l'ensemble de test (12 dernières semaines). Cette étape produit un DataFrame de prévisions exploitable qui servira de base à l'évaluation détaillée (section 2.3) et à la validation business (section 2.4).

**Contenu :**
- Génération des prédictions avec le modèle champion
- Construction d'un DataFrame de prévisions enrichi (Store, Dept, Date, réel vs prévu, erreur, semaines fériées)
- Statistiques descriptives des prévisions
- Aperçu des résultats (Top/Bottom erreurs)

</div>

In [ ]:
# ══════════════════════════════════════════════════════════════════════════════
# 2.2.4 — Génération des prévisions (modèle champion : XGBoost tuné)
# ══════════════════════════════════════════════════════════════════════════════
import numpy as np
import pandas as pd

print("=" * 70)
print("  GÉNÉRATION DES PRÉVISIONS — XGBoost (tuné)")
print("=" * 70)

# ── 1) Modèle champion ──────────────────────────────────────────────────────
champion_name = best_tuned[0]
champion_model = trained_models[champion_name]
print(f"\n  ► Modèle champion : {champion_name}")
print(f"  ► WMAE (test)     : {best_tuned[1]['WMAE']:,.0f} $")
print(f"  ► R² (test)       : {best_tuned[1]['R2']:.4f}")

# ── 2) Générer les prédictions finales ───────────────────────────────────────
print(f"\n── Prédictions sur l'ensemble de test ({X_test.shape[0]:,} lignes) ──")

y_pred_final = champion_model.predict(X_test)
print(f"  ✅ {len(y_pred_final):,} prévisions générées")

# ── 3) Construire le DataFrame de prévisions ────────────────────────────────
print("\n── Construction du DataFrame de prévisions ──")

df_predictions = pd.DataFrame({
    'Store':          df_train.loc[mask_test, 'Store_orig'].values,
    'Dept':           df_train.loc[mask_test, 'Dept_orig'].values,
    'Date':           df_train.loc[mask_test, 'Date'].values,
    'IsHoliday':      is_holiday_test,
    'Reel':           y_test.values,
    'Prevu':          y_pred_final,
})

# Colonnes dérivées
df_predictions['Erreur']     = df_predictions['Prevu'] - df_predictions['Reel']
df_predictions['Erreur_Abs'] = df_predictions['Erreur'].abs()
df_predictions['Erreur_Pct'] = (df_predictions['Erreur_Abs'] / df_predictions['Reel'].abs().replace(0, np.nan) * 100).round(2)

print(f"  ✅ DataFrame : {df_predictions.shape[0]:,} lignes × {df_predictions.shape[1]} colonnes")
print(f"  ► Colonnes   : {list(df_predictions.columns)}")

# ── 4) Statistiques descriptives des prévisions ─────────────────────────────
print(f"\n{'=' * 70}")
print("  STATISTIQUES DES PRÉVISIONS")
print(f"{'=' * 70}\n")

print(f"  ► Ventes réelles (test) :")
print(f"    Moyenne      : {df_predictions['Reel'].mean():>12,.0f} $")
print(f"    Médiane      : {df_predictions['Reel'].median():>12,.0f} $")
print(f"    Min          : {df_predictions['Reel'].min():>12,.0f} $")
print(f"    Max          : {df_predictions['Reel'].max():>12,.0f} $")

print(f"\n  ► Ventes prévues :")
print(f"    Moyenne      : {df_predictions['Prevu'].mean():>12,.0f} $")
print(f"    Médiane      : {df_predictions['Prevu'].median():>12,.0f} $")
print(f"    Min          : {df_predictions['Prevu'].min():>12,.0f} $")
print(f"    Max          : {df_predictions['Prevu'].max():>12,.0f} $")

print(f"\n  ► Erreurs absolues :")
print(f"    Moyenne (MAE): {df_predictions['Erreur_Abs'].mean():>12,.0f} $")
print(f"    Médiane      : {df_predictions['Erreur_Abs'].median():>12,.0f} $")
print(f"    90e centile  : {df_predictions['Erreur_Abs'].quantile(0.90):>12,.0f} $")
print(f"    95e centile  : {df_predictions['Erreur_Abs'].quantile(0.95):>12,.0f} $")
print(f"    Max          : {df_predictions['Erreur_Abs'].max():>12,.0f} $")

# Erreur médiane en %
median_pct = df_predictions['Erreur_Pct'].median()
print(f"\n  ► Erreur % médiane : {median_pct:.1f} %")

# ── 5) Répartition des erreurs ───────────────────────────────────────────────
print(f"\n{'=' * 70}")
print("  RÉPARTITION DES ERREURS")
print(f"{'=' * 70}\n")

seuils = [500, 1000, 2000, 5000]
for s in seuils:
    n = (df_predictions['Erreur_Abs'] <= s).sum()
    pct = n / len(df_predictions) * 100
    print(f"  ► Erreur ≤ {s:>5,} $ : {n:>6,} lignes ({pct:5.1f} %)")

# ── 6) Prévisions fériés vs normaux ─────────────────────────────────────────
print(f"\n{'=' * 70}")
print("  PRÉVISIONS : JOURS FÉRIÉS vs NORMAUX")
print(f"{'=' * 70}\n")

for label, mask_h in [("Normaux (IsHoliday=0)", df_predictions['IsHoliday'] == 0),
                       ("Fériés  (IsHoliday=1)", df_predictions['IsHoliday'] == 1)]:
    sub = df_predictions[mask_h]
    if len(sub) > 0:
        mae_h = sub['Erreur_Abs'].mean()
        med_h = sub['Erreur_Abs'].median()
        print(f"  ► {label} : {len(sub):,} lignes")
        print(f"    MAE     = {mae_h:,.0f} $")
        print(f"    Médiane = {med_h:,.0f} $\n")

# ── 7) Aperçu : meilleures et pires prévisions ──────────────────────────────
print(f"\n{'=' * 70}")
print("  TOP 10 — MEILLEURES PRÉVISIONS (erreur la plus faible)")
print(f"{'=' * 70}\n")

top10 = df_predictions.nsmallest(10, 'Erreur_Abs')[
    ['Store', 'Dept', 'Date', 'Reel', 'Prevu', 'Erreur', 'Erreur_Pct']
].copy()
top10['Reel']   = top10['Reel'].apply(lambda x: f"{x:,.0f} $")
top10['Prevu']  = top10['Prevu'].apply(lambda x: f"{x:,.0f} $")
top10['Erreur'] = top10['Erreur'].apply(lambda x: f"{x:+,.0f} $")
top10['Erreur_Pct'] = top10['Erreur_Pct'].apply(lambda x: f"{x:.2f} %")
top10.index = range(1, 11)
display(top10)

print(f"\n{'=' * 70}")
print("  TOP 10 — PIRES PRÉVISIONS (erreur la plus élevée)")
print(f"{'=' * 70}\n")

worst10 = df_predictions.nlargest(10, 'Erreur_Abs')[
    ['Store', 'Dept', 'Date', 'Reel', 'Prevu', 'Erreur', 'Erreur_Pct']
].copy()
worst10['Reel']   = worst10['Reel'].apply(lambda x: f"{x:,.0f} $")
worst10['Prevu']  = worst10['Prevu'].apply(lambda x: f"{x:,.0f} $")
worst10['Erreur'] = worst10['Erreur'].apply(lambda x: f"{x:+,.0f} $")
worst10['Erreur_Pct'] = worst10['Erreur_Pct'].apply(lambda x: f"{x:.2f} %")
worst10.index = range(1, 11)
display(worst10)

print(f"\n{'=' * 70}")
print(f"  ✅ DataFrame 'df_predictions' prêt ({df_predictions.shape[0]:,} lignes)")
print(f"{'=' * 70}")

  GÉNÉRATION DES PRÉVISIONS — XGBoost (tuné)

  ► Modèle champion : XGBoost
  ► WMAE (test)     : 1,304 $
  ► R² (test)       : 0.9850

── Prédictions sur l'ensemble de test (34,855 lignes) ──
  ✅ 34,855 prévisions générées

── Construction du DataFrame de prévisions ──
  ✅ DataFrame : 34,855 lignes × 9 colonnes
  ► Colonnes   : ['Store', 'Dept', 'Date', 'IsHoliday', 'Reel', 'Prevu', 'Erreur', 'Erreur_Abs', 'Erreur_Pct']

  STATISTIQUES DES PRÉVISIONS

  ► Ventes réelles (test) :
    Moyenne      :       15,686 $
    Médiane      :        7,510 $
    Min          :            0 $
    Max          :      194,032 $

  ► Ventes prévues :
    Moyenne      :       15,756 $
    Médiane      :        7,481 $
    Min          :          -10 $
    Max          :      182,529 $

  ► Erreurs absolues :
    Moyenne (MAE):        1,233 $
    Médiane      :          492 $
    90e centile  :        3,026 $
    95e centile  :        4,715 $
    Max          :       82,669 $

  ► Erreur % médiane : 8.6

,Store,Dept,Date,Reel,Prevu,Erreur,Erreur_Pct
1,16,60,2012-10-12,135 $,135 $,-0 $,0.01 %
2,13,50,2012-09-28,"1,952 $","1,952 $",+0 $,0.00 %
3,19,20,2012-09-21,"5,790 $","5,790 $",+0 $,0.00 %
4,5,35,2012-09-28,662 $,662 $,+0 $,0.01 %
5,31,59,2012-09-14,196 $,196 $,+0 $,0.03 %
6,25,80,2012-08-10,575 $,575 $,-0 $,0.02 %
7,43,9,2012-09-07,265 $,264 $,-0 $,0.05 %
8,31,59,2012-09-28,181 $,181 $,-0 $,0.07 %
9,7,28,2012-08-17,182 $,183 $,+0 $,0.08 %
10,5,36,2012-09-21,202 $,202 $,+0 $,0.08 %



  TOP 10 — PIRES PRÉVISIONS (erreur la plus élevée)



,Store,Dept,Date,Reel,Prevu,Erreur,Erreur_Pct
1,16,9,2012-10-19,"111,246 $","28,577 $","-82,669 $",74.31 %
2,13,3,2012-09-07,"114,231 $","45,787 $","-68,444 $",59.92 %
3,16,9,2012-10-26,"19,293 $","72,965 $","+53,672 $",278.19 %
4,41,3,2012-08-31,"23,535 $","71,609 $","+48,074 $",204.27 %
5,14,3,2012-09-14,"31,322 $","78,045 $","+46,724 $",149.17 %
6,12,3,2012-08-24,"87,707 $","44,111 $","-43,596 $",49.71 %
7,12,3,2012-09-07,"26,329 $","68,793 $","+42,464 $",161.28 %
8,10,3,2012-08-31,"27,278 $","68,432 $","+41,154 $",150.87 %
9,13,5,2012-08-24,"73,550 $","34,423 $","-39,127 $",53.20 %
10,4,72,2012-09-21,"127,832 $","90,176 $","-37,656 $",29.46 %



  ✅ DataFrame 'df_predictions' prêt (34,855 lignes)


<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

## <span id="23" style="color:#2E86C1;">2.3 Évaluation et validation des performances des modèles</span>

<div style="background:#1B2631; border-left:4px solid #2E86C1; padding:14px 18px; border-radius:8px; margin-top:12px; color:#D5D8DC;">

**Objectif :** Évaluer rigoureusement les performances du modèle champion (**XGBoost tuné**, WMAE = 1 332 $) à travers une batterie de métriques, des analyses visuelles et une interprétation des résultats. Cette section valide la qualité prédictive avant le déploiement.

**Plan de la section :**

| Sous-section | Contenu |
|:---|:---|
| **2.3.1** Choix des métriques | WMAE, MAE, RMSE, R², MAPE — justification et formules |
| **2.3.2** Comparaison des modèles | Tableau récapitulatif des 4 modèles (avant/après tuning), visualisations comparatives |
| **2.3.3** Analyse des erreurs | Distribution des résidus, erreurs par magasin/département, fériés vs normaux, scatter prévu vs réel |
| **2.3.4** Feature Importance & SHAP | Importance des variables (XGBoost natif), analyse SHAP pour l'interprétabilité |

**Données disponibles :**
- `df_predictions` : 34 855 prévisions (Store, Dept, Date, Réel, Prévu, Erreur, IsHoliday)
- `trained_models` : 4 modèles entraînés (Ridge, RF, LightGBM, XGBoost — les 2 derniers tunés)
- `df_results` : métriques initiales des 4 modèles
- `df_comparison` : avant/après tuning (XGBoost & LightGBM)

</div>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="231" style="color:#2E86C1;">2.3.1 Choix des métriques d'évaluation</span>

<div style="background:#1B2631; border-left:4px solid #2E86C1; padding:14px 18px; border-radius:8px; margin-top:12px; color:#D5D8DC;">

**Objectif :** Définir et justifier les métriques utilisées pour évaluer les modèles de prévision des ventes. Le choix de la **WMAE** comme métrique principale est dicté par le concours Kaggle Walmart, mais nous calculons également des métriques complémentaires pour une vision complète.

**Métriques retenues :**
- **WMAE** (Weighted MAE) — métrique principale, pondère ×5 les semaines fériées
- **MAE** (Mean Absolute Error) — erreur moyenne en dollars, interprétable directement
- **RMSE** (Root Mean Squared Error) — pénalise les grosses erreurs
- **R²** (Coefficient de détermination) — variance expliquée par le modèle
- **MAPE** (Mean Absolute Percentage Error) — erreur relative en %

</div>

In [ ]:
# ══════════════════════════════════════════════════════════════════════════════
# 2.3.1 — Choix des métriques d'évaluation
# ══════════════════════════════════════════════════════════════════════════════
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("=" * 70)
print("  MÉTRIQUES D'ÉVALUATION RETENUES")
print("=" * 70)

# ── 1) Rappel des formules ───────────────────────────────────────────────────

# ── 2) Calcul complet pour le champion (XGBoost tuné) ────────────────────────
print(f"── Métriques du champion : {champion_name} (tuné) ──\n")

y_true = y_test.values
y_pred_ch = y_pred_final

# WMAE
w_test = np.where(is_holiday_test == 1, 5, 1)
val_wmae = np.sum(w_test * np.abs(y_true - y_pred_ch)) / np.sum(w_test)

# MAE
val_mae = mean_absolute_error(y_true, y_pred_ch)

# RMSE
val_rmse = np.sqrt(mean_squared_error(y_true, y_pred_ch))

# R²
val_r2 = r2_score(y_true, y_pred_ch)

# MAPE (excluant les ventes nulles/négatives pour éviter division par 0)
mask_valid = np.abs(y_true) > 0
val_mape = np.mean(np.abs(y_true[mask_valid] - y_pred_ch[mask_valid]) / np.abs(y_true[mask_valid])) * 100
n_excluded = (~mask_valid).sum()

print(f"  ► WMAE  = {val_wmae:>10,.0f} $   ← métrique principale (Kaggle)")
print(f"  ► MAE   = {val_mae:>10,.0f} $   ← erreur absolue moyenne")
print(f"  ► RMSE  = {val_rmse:>10,.0f} $   ← sensible aux outliers")
print(f"  ► R²    = {val_r2:>10.4f}     ← variance expliquée")
print(f"  ► MAPE  = {val_mape:>10.2f} %   ← erreur relative moyenne")
if n_excluded > 0:
    print(f"    (MAPE calculé sur {mask_valid.sum():,} lignes, {n_excluded:,} exclues car ventes = 0)")

# ── 3) Tableau récapitulatif formaté ─────────────────────────────────────────
print(f"\n{'=' * 70}")
print("  TABLEAU RÉCAPITULATIF — CHAMPION")
print(f"{'=' * 70}\n")

df_metrics = pd.DataFrame([{
    'Métrique': 'WMAE (pondérée)',
    'Valeur': f"{val_wmae:,.0f} $",
    'Rôle': 'Métrique principale — pondère x5 les fériés',
}, {
    'Métrique': 'MAE',
    'Valeur': f"{val_mae:,.0f} $",
    'Rôle': 'Erreur moyenne en dollars',
}, {
    'Métrique': 'RMSE',
    'Valeur': f"{val_rmse:,.0f} $",
    'Rôle': 'Pénalise les grandes erreurs',
}, {
    'Métrique': 'R²',
    'Valeur': f"{val_r2:.4f}",
    'Rôle': f'{val_r2*100:.2f}% de la variance expliquée',
}, {
    'Métrique': 'MAPE',
    'Valeur': f"{val_mape:.2f} %",
    'Rôle': 'Erreur relative — interprétable par le métier',
}])
df_metrics.index = range(1, len(df_metrics) + 1)
display(df_metrics)



<div style="background:#1e1e2e; border-left:4px solid #f9e2af; padding:14px 18px; border-radius:8px; margin-top:12px; color:#cdd6f4;">

**Commentaire — Métriques d'évaluation :**

| Métrique | Valeur | Interprétation |
|:---|:---|:---|
| **WMAE** | **1 332 $** | En moyenne, l'erreur pondérée est de 1 332 $ par magasin/département/semaine |
| **MAE** | **1 263 $** | Sans pondération fériée, l'erreur descend — les fériés sont plus difficiles à prédire |
| **RMSE** | **2 801 $** | Le ratio RMSE/MAE ≈ 2.2 indique la présence de quelques erreurs importantes |
| **R²** | **0.9837** | Le modèle explique **98.4%** de la variance des ventes — excellente qualité |
| **MAPE** | **477 %** | ⚠️ Valeur gonflée par les départements à ventes quasi-nulles (division par ~0) |

**Observations :**
- Le **MAPE est non pertinent** ici en raison des ventes proches de 0 dans certains départements (ex: rayons saisonniers). C'est un phénomène classique — la MAPE n'est pas adaptée aux datasets avec des valeurs cibles proches de zéro.
- La **WMAE reste la métrique de référence** pour ce projet : interprétable, business-oriented, et robuste.
- Le **R² de 0.9837** confirme que le modèle capture la quasi-totalité de la dynamique des ventes.
- L'écart **WMAE > MAE** (+69 $) montre que les semaines fériées concentrent des erreurs plus élevées, ce qui est attendu.

</div>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="232" style="color:#2E86C1;">2.3.2 Comparaison des performances des modèles</span>

<div style="background:#1B2631; border-left:4px solid #2E86C1; padding:14px 18px; border-radius:8px; margin-top:12px; color:#D5D8DC;">

**Objectif :** Comparer les performances des 4 modèles (avant et après tuning) à l'aide de tableaux et de graphiques. Cette vue d'ensemble permet de justifier le choix du champion et de quantifier l'apport de l'ajustement des hyperparamètres.

**Contenu :**
- Tableau comparatif complet (6 modèles : 4 initiaux + 2 tunés)
- Graphique en barres : WMAE par modèle
- Graphique en barres : R² par modèle
- Classement final

</div>

In [ ]:
# ══════════════════════════════════════════════════════════════════════════════
# 2.3.2 — Comparaison des performances des modèles
# ══════════════════════════════════════════════════════════════════════════════
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd

print("=" * 70)
print("  COMPARAISON DES PERFORMANCES — 4 MODÈLES + TUNING")
print("=" * 70)

# ── 1) Construire le tableau comparatif complet ──────────────────────────────
# Résultats initiaux (section 2.2.2) — df_results contient les 4 modèles
# Résultats après tuning (section 2.2.3) — res_xgb, res_lgb

all_results = []

# Modèles initiaux
for _, row in df_results.iterrows():
    all_results.append({
        'Modèle': row['model'],
        'Version': 'Initial',
        'WMAE': row['WMAE'],
        'MAE': row['MAE'],
        'RMSE': row['RMSE'],
        'R2': row['R2'],
    })

# Modèles tunés
for name_m, res_m in [('XGBoost', res_xgb), ('LightGBM', res_lgb)]:
    all_results.append({
        'Modèle': name_m,
        'Version': 'Tuné',
        'WMAE': res_m['WMAE'],
        'MAE': res_m['MAE'],
        'RMSE': res_m['RMSE'],
        'R2': res_m['R2'],
    })

df_all = pd.DataFrame(all_results).sort_values('WMAE')
df_all.index = range(1, len(df_all) + 1)
df_all.index.name = 'Rang'

# Afficher le tableau formaté
df_show = df_all.copy()
df_show['WMAE'] = df_show['WMAE'].apply(lambda x: f"{x:,.0f} $")
df_show['MAE']  = df_show['MAE'].apply(lambda x: f"{x:,.0f} $")
df_show['RMSE'] = df_show['RMSE'].apply(lambda x: f"{x:,.0f} $")
df_show['R2']   = df_show['R2'].apply(lambda x: f"{x:.4f}")

print("\n── Classement final (6 configurations) ──\n")
display(df_show)

# ── 2) Graphique comparatif WMAE ─────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Préparer les labels
labels = [f"{r['Modèle']}\n({r['Version']})" for _, r in df_all.iterrows()]
wmaes = df_all['WMAE'].values
r2s = df_all['R2'].values

# Couleurs : champion en vert, tunés en bleu, initiaux en gris
colors = []
for _, r in df_all.iterrows():
    if r['Modèle'] == 'XGBoost' and r['Version'] == 'Tuné':
        colors.append('#27ae60')  # Champion — vert
    elif r['Version'] == 'Tuné':
        colors.append('#2980b9')  # Tuné — bleu
    else:
        colors.append('#7f8c8d')  # Initial — gris

# Graphique 1 : WMAE
ax1 = axes[0]
bars1 = ax1.barh(range(len(labels)), wmaes, color=colors, edgecolor='white', height=0.6)
ax1.set_yticks(range(len(labels)))
ax1.set_yticklabels(labels, fontsize=10)
ax1.set_xlabel('WMAE ($)', fontsize=12)
ax1.set_title('WMAE par modèle (plus bas = meilleur)', fontsize=13, fontweight='bold')
ax1.invert_yaxis()
ax1.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x:,.0f}'))

# Ajouter les valeurs sur les barres
for i, (bar, val) in enumerate(zip(bars1, wmaes)):
    ax1.text(val + 10, i, f'{val:,.0f} $', va='center', fontsize=10, fontweight='bold')

# Graphique 2 : R²
ax2 = axes[1]
bars2 = ax2.barh(range(len(labels)), r2s, color=colors, edgecolor='white', height=0.6)
ax2.set_yticks(range(len(labels)))
ax2.set_yticklabels(labels, fontsize=10)
ax2.set_xlabel('R²', fontsize=12)
ax2.set_title('R² par modèle (plus haut = meilleur)', fontsize=13, fontweight='bold')
ax2.invert_yaxis()
ax2.set_xlim(min(r2s) - 0.005, 1.0)

for i, (bar, val) in enumerate(zip(bars2, r2s)):
    ax2.text(val + 0.0003, i, f'{val:.4f}', va='center', fontsize=10, fontweight='bold')

plt.tight_layout()
plt.savefig('../images/232_comparaison_modeles.png', dpi=150, bbox_inches='tight')
plt.show()
print("  ✅ Graphique sauvegardé : images/232_comparaison_modeles.png")

# ── 3) Résumé ────────────────────────────────────────────────────────────────
champion_row = df_all.iloc[0]
print(f"\n{'=' * 70}")
print(f"  CHAMPION FINAL : {champion_row['Modèle']} ({champion_row['Version']})")
print(f"  WMAE = {champion_row['WMAE']:,.0f} $  |  R² = {champion_row['R2']:.4f}")
print(f"{'=' * 70}")

<div style="background:#1e1e2e; border-left:4px solid #f9e2af; padding:14px 18px; border-radius:8px; margin-top:12px; color:#cdd6f4;">

**Commentaire — Comparaison des performances :**

| Rang | Modèle | WMAE | R² | Observation |
|:---:|:---|:---|:---|:---|
| 1 | **XGBoost (Tuné)** | **1 332 $** | 0.9837 | Champion — meilleur WMAE |
| 2 | XGBoost (Initial) | 1 343 $ | 0.9836 | Tuning = −11 $ (−0.8%) |
| 3 | LightGBM (Tuné) | 1 357 $ | 0.9839 | Meilleur R² global, mais WMAE plus élevé |
| 4 | LightGBM (Initial) | 1 378 $ | 0.9837 | Tuning = −21 $ (−1.5%) |
| 5 | Random Forest | 1 381 $ | 0.9821 | Très proche de LightGBM |
| 6 | Ridge | 1 705 $ | 0.9762 | Baseline linéaire — distance = +373 $ |

**Observations clés :**
- **Tous les modèles R² > 0.976** — même le baseline Ridge offre une excellente qualité globale.
- Les **3 modèles ensemblistes** (RF, LightGBM, XGBoost) sont très proches : seulement **49 $** séparent le 2e du 5e rang.
- Le **tuning hyperparamétrique** a apporté des gains modestes (<2%) — confirmant que le **feature engineering** (lags, moyennes mobiles, target encoding) est le principal levier de performance.
- **XGBoost (Tuné)** est retenu comme champion malgré un R² légèrement inférieur à LightGBM (0.9837 vs 0.9839) car la WMAE est la métrique business prioritaire.

</div>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="233" style="color:#2E86C1;">2.3.3 Analyse des erreurs de prédiction</span>

<div style="background:#1B2631; border-left:4px solid #2E86C1; padding:14px 18px; border-radius:8px; margin-top:12px; color:#D5D8DC;">

**Objectif :** Analyser en profondeur les erreurs de prédiction du champion (XGBoost tuné) pour identifier les zones de force et de faiblesse du modèle. Cette analyse guide les améliorations futures et informe les utilisateurs métier des cas où le modèle est moins fiable.

**Visualisations :**
1. **Scatter plot** Prévu vs Réel — vérifier la linéarité
2. **Distribution des résidus** — vérifier la normalité et l'absence de biais
3. **Erreur par magasin** — identifier les magasins les plus difficiles à prédire
4. **Erreur fériés vs normaux** — quantifier l'impact des semaines fériées

</div>

In [ ]:
# ══════════════════════════════════════════════════════════════════════════════
# 2.3.3 — Analyse des erreurs de prédiction
# ══════════════════════════════════════════════════════════════════════════════
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd

print("=" * 70)
print("  ANALYSE DES ERREURS DE PRÉDICTION — XGBoost (tuné)")
print("=" * 70)

residus = df_predictions['Erreur'].values       # Prévu - Réel
erreur_abs = df_predictions['Erreur_Abs'].values

# ══════════════════════════════════════════════════════════════════════════════
# Figure 1 : Scatter Prévu vs Réel + Distribution des résidus
# ══════════════════════════════════════════════════════════════════════════════
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# 1a) Scatter : Prévu vs Réel
ax1 = axes[0]
ax1.scatter(df_predictions['Reel'], df_predictions['Prevu'],
            alpha=0.08, s=4, c='#2980b9', rasterized=True)
lims = [min(df_predictions['Reel'].min(), df_predictions['Prevu'].min()),
        max(df_predictions['Reel'].max(), df_predictions['Prevu'].max())]
ax1.plot(lims, lims, 'r--', linewidth=1.5, label='Prédiction parfaite')
ax1.set_xlabel('Ventes réelles ($)', fontsize=11)
ax1.set_ylabel('Ventes prévues ($)', fontsize=11)
ax1.set_title('Prévu vs Réel — XGBoost (tuné)', fontsize=13, fontweight='bold')
ax1.legend(fontsize=10)
ax1.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x/1000:.0f}k'))
ax1.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x/1000:.0f}k'))

# 1b) Distribution des résidus
ax2 = axes[1]
# Clip à +/- 10000 pour lisibilité
clip_res = np.clip(residus, -10000, 10000)
ax2.hist(clip_res, bins=100, color='#2980b9', edgecolor='white', alpha=0.8)
ax2.axvline(0, color='red', linestyle='--', linewidth=1.5, label='Biais = 0')
ax2.axvline(np.mean(residus), color='orange', linestyle='-', linewidth=1.5,
            label=f'Biais moyen = {np.mean(residus):+,.0f} $')
ax2.set_xlabel('Résidu (Prévu - Réel) en $', fontsize=11)
ax2.set_ylabel('Fréquence', fontsize=11)
ax2.set_title('Distribution des résidus', fontsize=13, fontweight='bold')
ax2.legend(fontsize=10)

plt.tight_layout()
plt.savefig('../images/233_scatter_residus.png', dpi=150, bbox_inches='tight')
plt.show()
print("  ✅ Figure 1 sauvegardée : images/233_scatter_residus.png")

# ══════════════════════════════════════════════════════════════════════════════
# Figure 2 : Erreur moyenne par magasin (Top 10 pires + Top 10 meilleurs)
# ══════════════════════════════════════════════════════════════════════════════
print(f"\n{'=' * 70}")
print("  ERREUR MOYENNE PAR MAGASIN")
print(f"{'=' * 70}\n")

store_mae = df_predictions.groupby('Store')['Erreur_Abs'].mean().sort_values()
best_stores = store_mae.head(10)
worst_stores = store_mae.tail(10)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Meilleurs magasins
ax3 = axes[0]
ax3.barh(range(len(best_stores)), best_stores.values, color='#27ae60', height=0.6)
ax3.set_yticks(range(len(best_stores)))
ax3.set_yticklabels([f'Store {int(s)}' for s in best_stores.index], fontsize=10)
ax3.set_xlabel('MAE moyenne ($)', fontsize=11)
ax3.set_title('Top 10 — Meilleurs magasins', fontsize=13, fontweight='bold')
for i, v in enumerate(best_stores.values):
    ax3.text(v + 10, i, f'{v:,.0f} $', va='center', fontsize=9)

# Pires magasins
ax4 = axes[1]
ax4.barh(range(len(worst_stores)), worst_stores.values, color='#e74c3c', height=0.6)
ax4.set_yticks(range(len(worst_stores)))
ax4.set_yticklabels([f'Store {int(s)}' for s in worst_stores.index], fontsize=10)
ax4.set_xlabel('MAE moyenne ($)', fontsize=11)
ax4.set_title('Top 10 — Pires magasins', fontsize=13, fontweight='bold')
for i, v in enumerate(worst_stores.values):
    ax4.text(v + 10, i, f'{v:,.0f} $', va='center', fontsize=9)

plt.tight_layout()
plt.savefig('../images/233_erreur_par_magasin.png', dpi=150, bbox_inches='tight')
plt.show()
print("  ✅ Figure 2 sauvegardée : images/233_erreur_par_magasin.png")

print(f"\n  ► Meilleur magasin : Store {int(best_stores.index[0])} — MAE = {best_stores.values[0]:,.0f} $")
print(f"  ► Pire magasin    : Store {int(worst_stores.index[-1])} — MAE = {worst_stores.values[-1]:,.0f} $")
print(f"  ► Ratio pire/meilleur : {worst_stores.values[-1]/best_stores.values[0]:.1f}x")

# ══════════════════════════════════════════════════════════════════════════════
# Figure 3 : Comparaison Fériés vs Normaux
# ══════════════════════════════════════════════════════════════════════════════
print(f"\n{'=' * 70}")
print("  ERREURS : FÉRIÉS vs NORMAUX")
print(f"{'=' * 70}\n")

normal = df_predictions[df_predictions['IsHoliday'] == 0]['Erreur_Abs']
holiday = df_predictions[df_predictions['IsHoliday'] == 1]['Erreur_Abs']

stats_comparison = pd.DataFrame({
    'Métrique': ['N lignes', 'MAE moyenne', 'MAE médiane', '90e centile', '95e centile'],
    'Normaux': [
        f"{len(normal):,}",
        f"{normal.mean():,.0f} $",
        f"{normal.median():,.0f} $",
        f"{normal.quantile(0.90):,.0f} $",
        f"{normal.quantile(0.95):,.0f} $",
    ],
    'Fériés': [
        f"{len(holiday):,}",
        f"{holiday.mean():,.0f} $",
        f"{holiday.median():,.0f} $",
        f"{holiday.quantile(0.90):,.0f} $",
        f"{holiday.quantile(0.95):,.0f} $",
    ],
})
stats_comparison.index = range(1, len(stats_comparison) + 1)
display(stats_comparison)

# Boxplot comparatif
fig, ax = plt.subplots(figsize=(8, 5))
data_bp = [normal.clip(upper=normal.quantile(0.99)).values,
           holiday.clip(upper=holiday.quantile(0.99)).values]
bp = ax.boxplot(data_bp, labels=['Normaux', 'Fériés'], patch_artist=True,
                widths=0.5, showfliers=False)
bp['boxes'][0].set_facecolor('#3498db')
bp['boxes'][1].set_facecolor('#e74c3c')
for box in bp['boxes']:
    box.set_alpha(0.7)
ax.set_ylabel('Erreur absolue ($)', fontsize=12)
ax.set_title('Distribution des erreurs : Normaux vs Fériés (99e centile)', fontsize=13, fontweight='bold')
ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x:,.0f}'))
plt.tight_layout()
plt.savefig('../images/233_feries_vs_normaux.png', dpi=150, bbox_inches='tight')
plt.show()
print("  ✅ Figure 3 sauvegardée : images/233_feries_vs_normaux.png")

# ── Résumé statistique ───────────────────────────────────────────────────────
print(f"\n{'=' * 70}")
print("  RÉSUMÉ DE L'ANALYSE DES ERREURS")
print(f"{'=' * 70}")
print(f"\n  ► Biais moyen (résidus)     : {np.mean(residus):+,.0f} $")
print(f"  ► Écart-type des résidus    : {np.std(residus):,.0f} $")
print(f"  ► % erreurs < 1 000 $       : {(erreur_abs < 1000).sum()/len(erreur_abs)*100:.1f}%")
print(f"  ► % erreurs < 2 000 $       : {(erreur_abs < 2000).sum()/len(erreur_abs)*100:.1f}%")
print(f"  ► MAE fériés / MAE normaux  : {holiday.mean()/normal.mean():.2f}x")

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="234" style="color:#2E86C1;">2.3.4 Interprétation avec Feature Importance et SHAP</span>

<div style="background:#1B2631; border-left:4px solid #2E86C1; padding:14px 18px; border-radius:8px; margin-top:12px; color:#D5D8DC;">

**Objectif :** Comprendre **pourquoi** le modèle fait ses prédictions en analysant l'importance des variables. Cette interprétabilité est cruciale pour la confiance des utilisateurs métier et la validation scientifique du modèle.

**Méthodes :**
- **Feature Importance (XGBoost natif)** — importance basée sur le gain (réduction de l'erreur apportée par chaque variable lors des splits)
- **SHAP (SHapley Additive exPlanations)** — valeurs de Shapley qui mesurent la contribution marginale de chaque variable à chaque prédiction individuelle

</div>

In [ ]:
# ══════════════════════════════════════════════════════════════════════════════
# 2.3.4 — Feature Importance (XGBoost) + SHAP
# ══════════════════════════════════════════════════════════════════════════════
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd
import shap

print("=" * 70)
print("  FEATURE IMPORTANCE & SHAP — XGBoost (tuné)")
print("=" * 70)

# ══════════════════════════════════════════════════════════════════════════════
# 1) Feature Importance native (gain)
# ══════════════════════════════════════════════════════════════════════════════
print("\n── 1) Feature Importance native (XGBoost — gain) ──\n")

importances = champion_model.feature_importances_
feat_names = feature_cols

df_imp = pd.DataFrame({
    'Feature': feat_names,
    'Importance': importances
}).sort_values('Importance', ascending=False)
df_imp['Pct'] = (df_imp['Importance'] / df_imp['Importance'].sum() * 100).round(2)
df_imp['Cumul'] = df_imp['Pct'].cumsum().round(2)
df_imp.index = range(1, len(df_imp) + 1)

# Afficher Top 15
print("  Top 15 variables :\n")
df_imp_show = df_imp.head(15).copy()
df_imp_show['Importance'] = df_imp_show['Importance'].apply(lambda x: f"{x:.4f}")
df_imp_show['Pct'] = df_imp_show['Pct'].apply(lambda x: f"{x:.2f} %")
df_imp_show['Cumul'] = df_imp_show['Cumul'].apply(lambda x: f"{x:.2f} %")
display(df_imp_show)

# Graphique Feature Importance
fig, ax = plt.subplots(figsize=(10, 8))
top20 = df_imp.head(20).iloc[::-1]  # Inverser pour le barh
colors = ['#27ae60' if i < 5 else '#2980b9' if i < 10 else '#7f8c8d'
          for i in range(len(top20))][::-1]
ax.barh(range(len(top20)), top20['Importance'].astype(float).values,
        color=colors, edgecolor='white', height=0.65)
ax.set_yticks(range(len(top20)))
ax.set_yticklabels(top20['Feature'].values, fontsize=10)
ax.set_xlabel('Importance (gain)', fontsize=12)
ax.set_title('Top 20 — Feature Importance (XGBoost tuné)', fontsize=14, fontweight='bold')
for i, v in enumerate(top20['Importance'].astype(float).values):
    ax.text(v + 0.001, i, f'{v:.3f}', va='center', fontsize=9)

plt.tight_layout()
plt.savefig('../images/234_feature_importance.png', dpi=150, bbox_inches='tight')
plt.show()
print("  ✅ Feature Importance sauvegardée : images/234_feature_importance.png")

# ══════════════════════════════════════════════════════════════════════════════
# 2) SHAP — Valeurs de Shapley
# ══════════════════════════════════════════════════════════════════════════════
print(f"\n{'=' * 70}")
print("  SHAP — ANALYSE DES VALEURS DE SHAPLEY")
print(f"{'=' * 70}\n")

# Échantillon pour SHAP (calcul intensif sur 34k lignes)
shap_sample_size = min(2000, len(X_test))
np.random.seed(42)
shap_idx = np.random.choice(len(X_test), shap_sample_size, replace=False)
X_shap = X_test.iloc[shap_idx]

print(f"  ► Calcul SHAP sur {shap_sample_size:,} observations (échantillon du test)...")

# TreeExplainer (optimisé pour les modèles à base d'arbres)
explainer = shap.TreeExplainer(champion_model)
shap_values = explainer.shap_values(X_shap)

print(f"  ✅ SHAP values calculées : shape = {shap_values.shape}")

# 2a) SHAP Summary Plot (beeswarm)
print("\n── SHAP Summary Plot (beeswarm) ──")
fig, ax = plt.subplots(figsize=(10, 8))
shap.summary_plot(shap_values, X_shap, feature_names=feature_cols,
                  show=False, max_display=20)
plt.title('SHAP Summary Plot — Impact des variables sur les prévisions',
          fontsize=13, fontweight='bold', pad=20)
plt.tight_layout()
plt.savefig('../images/234_shap_summary.png', dpi=150, bbox_inches='tight')
plt.show()
print("  ✅ SHAP Summary sauvegardé : images/234_shap_summary.png")

# ── 3) Résumé : Top 10 SHAP vs Feature Importance ───────────────────────────
print(f"\n{'=' * 70}")
print("  COMPARAISON : TOP 10 FEATURE IMPORTANCE vs SHAP")
print(f"{'=' * 70}\n")

shap_imp = np.abs(shap_values).mean(axis=0)
df_shap = pd.DataFrame({
    'Feature': feature_cols,
    'SHAP_mean_abs': shap_imp,
}).sort_values('SHAP_mean_abs', ascending=False)
df_shap.index = range(1, len(df_shap) + 1)

# Comparer Top 10
top10_fi = list(df_imp.head(10)['Feature'])
top10_shap = list(df_shap.head(10)['Feature'])

print("  Feature Importance (gain)    │  SHAP (|mean|)")
print("  " + "─" * 30 + "┼" + "─" * 30)
for i in range(10):
    fi_name = top10_fi[i] if i < len(top10_fi) else ''
    sh_name = top10_shap[i] if i < len(top10_shap) else ''
    match = " ✓" if fi_name == sh_name else ""
    print(f"  {i+1:2d}. {fi_name:27s} │ {i+1:2d}. {sh_name:20s}{match}")

common = set(top10_fi) & set(top10_shap)
print(f"\n  ► Variables communes dans les Top 10 : {len(common)}/10")
print(f"  ► Liste : {sorted(common)}")



<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

## <span id="24" style="color:#2E86C1;">2.4 Validation métier des prévisions déployées</span>

<div style="background:#1B2631; border-left:4px solid #2E86C1; padding:14px 18px; border-radius:8px; margin-bottom:10px; color:#D5D8DC;">

**Objectif** — Vérifier que les prévisions du modèle champion (XGBoost tuné, WMAE = 1 332 $) sont **utilisables en pratique** par les gestionnaires de stocks et d'approvisionnement.

Contrairement à la validation **technique** (section 2.3) qui évalue les métriques statistiques, la validation **métier** répond à une question différente : *"Ces prévisions sont-elles fiables pour prendre des décisions de gestion ?"*

| Sous-section | Question métier |
|---|---|
| **2.4.1** Cohérence | Les prévisions ont-elles un sens ? (valeurs aberrantes, biais) |
| **2.4.2** Historique | Les prévisions respectent-elles les tendances passées ? |
| **2.4.3** Verdict final | Seuils de tolérance GO/NO-GO pour la mise en production |

</div>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="241" style="color:#2E86C1;">2.4.1 Analyse de la cohérence des prévisions déployées</span>

<div style="background:#1B2631; border-left:4px solid #2E86C1; padding:14px 18px; border-radius:8px; margin-top:12px; color:#D5D8DC;">

**Objectif** — Vérifier la **cohérence interne** des prévisions déployées avant tout usage décisionnel :

- Détection des prévisions négatives ou aberrantes
- Analyse du biais systématique (sur- ou sous-estimation globale)
- Taux de couverture par seuil d'erreur relative
- Comparaison visuelle de la distribution Réel vs Prévu

</div>

In [ ]:
from pathlib import Path
import os

# Check structure
print("Working Directory:", os.getcwd())
print("\nCheck DATA_DIR:")
data_path = Path('../Data')
print(f"  Exists: {data_path.exists()}")
if data_path.exists():
    print(f"  Contents: {list(data_path.glob('*.csv'))}")

print("\nCheck notebook location:")
print(f"  This should be in: walmart-sales-forecasting/notebooks/")
print(f"  Actual parent: {Path('.').resolve().parent}")



Working Directory: c:\Users\fband\OneDrive - Collège la Cité\Documents\000Semestre 04\004 Projet Sciences des données\Projet Integrateur\UA2\walmart-sales-forecasting\notebooks

Check DATA_DIR:
  Exists: True
  Contents: [WindowsPath('../Data/features.csv'), WindowsPath('../Data/stores.csv'), WindowsPath('../Data/test.csv'), WindowsPath('../Data/train.csv')]

Check notebook location:
  This should be in: walmart-sales-forecasting/notebooks/
  Actual parent: C:\Users\fband\OneDrive - Collège la Cité\Documents\000Semestre 04\004 Projet Sciences des données\Projet Integrateur\UA2\walmart-sales-forecasting

Check df_predictions:
  Exists: True
  Shape: (34855, 9)
  Columns: ['Store', 'Dept', 'Date', 'IsHoliday', 'Reel', 'Prevu', 'Erreur', 'Erreur_Abs', 'Erreur_Pct']

Check packages:
  pandas: 2.3.3
  numpy: 2.4.1


<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="242" style="color:#2E86C1;">2.4.2 Comparaison avec les ventes historiques</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="243" style="color:#2E86C1;">2.4.3 Validation finale par les utilisateurs métier</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

<br>

<center>
<span id="3" style="color:#E67E22;">
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br>
<strong style="font-size:19px;">
Intelligence décisionnelle & exploitation
</strong><br>
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
</span>
</center>

## <span id="31" style="color:#2E86C1;">3.1 Déploiement du modèle de prévision</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="311" style="color:#2E86C1;">3.1.1 Choix du mode de restitution (rapport, dashboard, fichier)</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="312" style="color:#2E86C1;">3.1.2 Mise à disposition des prévisions générées</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="313" style="color:#2E86C1;">3.1.3 Documentation du fonctionnement du modèle</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="314" style="color:#2E86C1;">3.1.4 Définition des limites et hypothèses du modèle</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

## <span id="32" style="color:#2E86C1;">3.2 Générer des prévisions de ventes pour la planification</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="321" style="color:#2E86C1;">3.2.1 Générer prévisions par magasin</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="322" style="color:#2E86C1;">3.2.2 Générer prévisions par département</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="323" style="color:#2E86C1;">3.2.3 Documenter méthodologie prévisions</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

## <span id="33" style="color:#2E86C1;">3.3 Créer un système de recommandations pour la gestion</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="331" style="color:#2E86C1;">3.3.1 Calculer niveaux de stock optimaux</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="332" style="color:#2E86C1;">3.3.2 Générer alertes de rupture</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="333" style="color:#2E86C1;">3.3.3 Produire rapports recommandations</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

## <span id="34" style="color:#2E86C1;">3.4 Développer un simulateur d'impact des promotions</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="341" style="color:#2E86C1;">3.4.1 Créer interface de simulation</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="342" style="color:#2E86C1;">3.4.2 Calculer impact prévisionnel</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="343" style="color:#2E86C1;">3.4.3 Estimer ROI et comparer scénarios</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

## <span id="35" style="color:#2E86C1;">3.5 Créer un dashboard de visualisation et monitoring</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="351" style="color:#2E86C1;">3.5.1 Développer visualisations principales</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="352" style="color:#2E86C1;">3.5.2 Créer cartes KPIs exécutifs</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>

### <span id="353" style="color:#2E86C1;">3.5.3 Implémenter filtres et interactivité</span>

<a href="#0" style="color:#5D6D7E; text-decoration:none;">
↑ Retour au sommaire
</a>